### ISSUE TITLE
Employer's Preference for Credentials, Learning Opps, Assessments, Competency Frameworks

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#411]
Consult with Bob to determine if CTDL needs a property to indicate employer preference.

**Comment by stuartasutton** [comment]
Jeanne, can you say a bit more about what this means? Employer preference as to what?

**Comment by jkitchensSIUC** [comment]
This is a type of quality.  

This employer prefers this credential.
This employer prefers this competency framework.
This employer prefers this assessment.
This employer prefers this learning opportunity.

**Comment by stuartasutton** [comment]
Per the last bullets above, here are some suggestions for revision of CredentialOrganization and QACredentialOrganization:

**CredentialOrganization:**

>**Description:** An organization that plays one or more primary roles in the lifecycle of a credential including creation, maintenance, and offering.
**Comment:** A credentialing organization may also play a secondary role in quality assurance through the explicit preferencing of credentials, assessments and learning opportunities. 

**QACredentialingOrganization:**

> **Description:** An organization whose primary role is providing explicit quality assurance for credentials, assessment, learning opportunities, and organizations.
**Comment:** A quality assurance organization may also play a secondary role as a credentialing organization.

**Comment by siuc-nate** [comment]
Current proposal:

- Modify the definition of QACredentialOrganization: "An organization that primarily plays one or more quality assurance roles in relation to a resource."
- Add a comment to QACredentialOrganization: "Includes organizations that play formal roles such as accrediting or regulating and informal roles such as preferring or recognizing."
- Modify the definition of CredentialOrganization: "An organization that primarily plays one or more roles in the lifecycle of a credential."
- Add a comment to CredentialOrganization: "Includes organizations that create, maintain, or offer credentials"
- Alternatively, explore creating a new class, i.e., "Employer", that would primarily perform informal QA functions in the context of CTDL
- Extend the domain of ceterms:requires to include ceterms:QACredentialOrganization
- Create these terms:

**URI:** ceterms:preferredBy
**Label:** Preferred By
**Definition:** An agent that prefers the described resource over other similar resources.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
**Range:** ceterms:QACredentialOrganization

**URI:** ceterms:preferredIn
**Label:** Preferred In
**Definition:** The resource being described is favored over other similar resources in the jurisdiction being referenced.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
**Range:** ceterms:JurisdictionProfile

**URI:** ceterms:prefers
**Label:** Prefers
**Definition:** The agent being described favors the resource being referenced over other similar resources.
**Domain:** ceterms:QACredentialOrganization
**Range:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile

**URI:** ceterms:PreferAction
**Label:** Prefer Action
**Definition:** An action by an agent indicating preference of a resource.

**URI:** ceterms:requiredBy
**Label:** Required By
**Definition:** An agent that requires the described resource.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile 
**Range:** ceterms:QACredentialOrganization

**URI:** ceterms:requiredIn
**Label:** Required In
**Definition:** The resource being described is required in the jurisdiction being referenced.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
**Range:** ceterms:JurisdictionProfile

**URI:** ceterms:RequiredAction
**Label:** Required Action
**Definition:** An action by an agent indicating the requirement of a resource.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate this is to add more information to update the above proposal.  

The major Credential Engine employer use cases enable employers to signal the value or quality of a credential by asserting whether they require, prefer or otherwise recognize a credential for making decisions on hiring or promoting individuals.  **This is addressed with the above comment.** 

Other forms of recognition may be:
- employer  involvement in hiring from credential organizations (we hire from here) **(this would require a new property)**
- employer serving on advisory groups. 

Three major questions for the Business Advisory and QA Advisory are:

1. Should credentialing organizations be enabled to make assertions about which employers have recognized their credentials similar to how some now list employer logos as partners on their websites and how they can now assert that they are accredited, approved, or endorsed by a Quality Assurance organization.
2. If so, what are the full range employer signaling actions that should be captured?  For example, should we provide a list of actions such as require, prefer, and recognize?
3. Should Credential Engine work with employer application developers to use CTDL to capture employer signaling directly that could confirm these assertions similar to how QA organizations publish their actions to the registry to confirm assertions by credentialing organizations?    If so, how should this be designed and tested?

**Comment by siuc-nate** [comment]
We should discuss this on Tuesday.

**Comment by siuc-nate** [comment]
Per our 8/8/2017 conversation, we need to review @jkitchensSIUC's questions to ensure they cover all the bases we need to cover.

**Comment by jkitchensSIUC** [comment]
Updated [Employer Signaling: Requiring, Preferring or Recognizing Credentials document](https://drive.google.com/file/d/0B1uSTaYpjhXJTW1MMmVnX0ItRVE/view?usp=sharingl)t to plan and move forward with solutions.

**Comment by siuc-nate** [comment]
see also #556

**Comment by siuc-nate** [comment]
We've done fine since 2017 without this - I recommend we close this.

**Comment by siuc-nate** [comment]
Closing this, as nothing has happened with it since 2017.
