### ISSUE TITLE
Add altIdentifier property to CTDL-ASN

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#599]
Currently, we have a ['ceasn:identifier'](https://credreg.net/ctdlasn/terms#identifier) property that is **properly** defined as follows:

>*An alternative URI by which this competency framework or competency is identified.*

This definition is useful as is with its range of `xsd:anyURI`. Think of the US Common Core State Standards that have their canonical URI's and ASN which includes the canonical URI as a `ceasn:identifier` in its data.

However, in addition, there are needs to include additional non-URI identifiers such as the following for the EU's *Entrepreneurship Competency Framework*:
* EUR 27939 EN
* ISBN 978-92-79-58538-8
* ISMN 1831-9424
* doi:10.2791/593884
* LF-NA-27939-EN-N

I absolutely do not think we need to define separate properties for such identifiers or create some alternative mechanism at this time (i.e., some separate description entity) to provide information beyond the text of the identifier...and that precludes use of `ceasn:CredentialAlignmentObject` or even `schema:DefinedTerm`.

We should add the following:

>**URI:**` ceasn:altIdentifier`
**Label:** Alternative Identifier
**Description:** *Property for representing any kind of identifier as a textual string.*
**Domain Includes:** `ceasn:CompetencyFramework`, `ceasn:ConceptScheme`
**Range Includes:** `xsd:string`
**Equivalent Property:** https://schema.org/identifier
**UsageNote:** *For URI identifiers for the resource being described that are alternatives to the `@id`used in JSON-LD encoding, use `ceasn:identifier`*.

**Comment by siuc-nate** [comment]
Is this already covered by [ceasn:codedNotation](https://credreg.net/ctdlasn/terms/codedNotation) and/or [ceasn:altCodedNotation](https://credreg.net/ctdlasn/terms/altCodedNotation)?

**ceasn:codedNotation**: An alphanumeric notation or ID code as defined by the promulgating body to identify this resource.

**ceasn:altCodedNotation**: An alphanumeric notation or ID code identifying this competency in common use among end-users.

**Comment by stuartasutton** [comment]
No, Nate. Coded notation is a one form--a very specific form--of identifier like "CCSS.ELA-LITERACY.SL.6.2" in the Common Core State Standards or a Dewey Decimal number. These are other identifiers that, as you can see from above, aren't of that sort.

**Comment by siuc-nate** [comment]
They all look like "alphanumeric notation or ID code" to me.  How would publishers/consumers be able to tell the difference and know which data goes in what property?

**Comment by stuartasutton** [comment]
Structurally, yes, they look alike...so does a jackass and a horse....but best not confuse them :-)

**Comment by siuc-nate** [comment]
I'm looking over those codes again and trying to figure out how I would tell a publisher which one to use for some piece of data. All of your examples look like externally-maintained codes, so is it correct to say something like:
"codedNotation/altCodedNotation is for identifiers used by the organization to identify its own stuff; identifier/altIdentifier is for identifiers issued by a third party to that organization's stuff"?  

I'm not sure if that's an intentional difference or a coincidence but I can see it being meaningful, even if it still feels like splitting hairs.

**Comment by philbarker** [comment]
@stuartasutton for clarity, are you suggesting that the value of the alt identifier would be something like "ISBN 978-92-79-58538-8" and not just "978-92-79-58538-8"
It makes sense to me to keep the coded notation for the Common Core dot-codes, but perhaps change the definition to make this clear?

**Comment by siuc-nate** [comment]
@phil for something like that, I would recommend separating the type of identifier (ISBN) from the identifier itself.  Something like [ceterms:IdentifierValue](https://credreg.net/ctdl/terms/IdentifierValue) exists for that purpose; perhaps it could be considered here.

**Comment by stuartasutton** [comment]
Yes, Phil, "ISBN 978-92-79-58538-8" is more like it. Nate, use of [ceterms:IdentifierValue](https://credreg.net/ctdl/terms/IdentifierValue) --defined in the Credential context-- is exactly what I am trying to avoid in the competency framework context...i.e., avoid a proliferation of classes. In the Navy CRADA profile work, we are likely facing some proliferation, but I am trying to constrain the complexity of the core competency framework specification.

**Comment by siuc-nate** [comment]
Mixing different pieces of data together in the same string like that will make them more or less useless in any programmatic context.
```
ISBN 978-92-79-58538-8
ISBN: 978-92-79-58538-8
ISBN - 978-92-79-58538-8
978-92-79-58538-8 (ISBN)
ISBN:978-92-79-58538-8
ISBN_9789279585388
978-92-79-58538-8
```
And other such variants of potential values make fields like that effectively dead/dumb string fields that can't be reliably worked with programmatically.

**Comment by stuartasutton** [comment]
Yes, that is correct. But the point here is to document related identifiers, not to do anything programmatically with them.

**Comment by siuc-nate** [comment]
I'm not sure I understand the usefulness of documenting them if you can't do anything with them afterwards (besides displaying the raw data perhaps?).  Even just displaying the data would benefit from separating the label and the identifier itself (particularly if the identifier has a known resolution service).  For example, compare the usefulness of some web page that displays this:

**Identifiers**
EUR 27939 EN
ISBN 978-92-79-58538-8
ISMN 1831-9424
doi:10.2791/593884
LF-NA-27939-EN-N

vs this:

**Identifiers**
**ISBN:** [978-92-79-58538-8](https://isbnsearch.org/isbn/9789279585388)
**ISMN:** 1831-9424
**DOI:** [doi:10.2791/593884](https://publications.europa.eu/en/publication-detail/-/publication/5e633083-27c8-11e6-914b-01aa75ed71a1/language-en)
**Other:** LF-NA-27939-EN-N
**Other:** EUR 27939 EN

As seen on the [site](https://ec.europa.eu/jrc/en/publication/eur-scientific-and-technical-research-reports/entrecomp-entrepreneurship-competence-framework) some of these identifiers come from:
![image](https://user-images.githubusercontent.com/21346519/56607364-ff73f000-65cd-11e9-86aa-3614a3cc38b4.png)

**Comment by Lomilar** [comment]
I'd recommend mapping altIdentifier if you do make it to schema:identifier.

**Comment by stuartasutton** [comment]
Let me explain further the context and the problem to be solved. In both ASN and CTDL-ASN, there are two properties for "identifiers": (1) [`ceasn:identifier`](http://purl.org/ctdlasn/terms/identifier) -- an alternative URI for a framework or competency such as the canonical Common Core URI for a Math competency or an ISBN identifier by URI; and (2) `codedNotation` (and alt coded Notation)-- used in the same manner as [`skos:notation`](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#notations) for formal codes like a Dewey Decimal Number or a Library of Congress Classification Number or the code assigned to a Common Core competency (e.g., "CCSS.ELA-LITERACY.SL.6.2"). 

That's it! There is no further facility in ASN or CTDL-ASN to include other associated (minor) identifiers like those listed in this issue's framing. The proposal `altIdentifier` as literal was to fill that gap in a manner commensurate with the problem and solution...e.g., "ISBN 978-92-79-58538-8".

I am really reluctant, without due consideration, to start down the path of classes like Schema.org's `DefinedTerm`/`CategoryTerm` in this context. As linked data schemas, preference for 2 decades has been for things like concepts, competencies etc. to be either a literal or an object property pointing off to where the object data can be found, retrieved and processed. The minor identifiers of this issue could be handled in the same way...as simple literals (see ISBN above) or by object property references via the existing `ceasn:identifier` (should an ISBN have a resolvable URI).

**Comment by siuc-nate** [comment]
I don't want to add complexity to the schema either, but mixing data like that breaks the pattern we've established everywhere else and seems like a failure to atomize data properly.

In my opinion, if the data is meant to be captured, documented, interpreted, and otherwise treated as a simple "dumb" string, use `codedNotation`.  If the data can be resolved directly (e.g. it is both a URI and a URL) use `identifier`. If the data is a "complex" string with multiple components (like the code itself along with the type of code), use an object and embody each property of the data as a property of the object.

In my current work with converting CTDL to EOCred, I've ended up using schema:PropertyValue to convey CTIDs like so:
```
{
  "@type": "schema:EducationalOccupationalCredential",
  "schema:identifier": {
    "@type": "schema:PropertyValue",
    "schema:name": "Credential Transparency Identifier",
    "schema:alternateName": "CTID",
    "schema:value": "ce-a7f6202e-070b-462c-ab05-e5dc1d9f21f9",
    "schema:identifier": "ce-a7f6202e-070b-462c-ab05-e5dc1d9f21f9",
    "schema:propertyID": "https://purl.org/ctdl/terms/ctid"
  }
}
```
It's probably overkill and I still haven't figured out whether the CTID belongs in `value` or `identifier`, but a consuming system would also be able to pick out CTIDs from the data with 100% certainty that it had interpreted it correctly.

Another example would be our handling of cost information in CTDL.  Even though it would be a lot simpler to publish a string like `"ceterms:price": "$100"`, that string is really _two_ pieces of data, so we treat it that way by breaking it out into `ceterms:price` and `ceterms:currency`. Following in the same logic as my [previous post](https://github.com/CredentialEngine/vocabularies/issues/599#issuecomment-485848816), this avoids a situation where a consuming system has to try to parse values like:
```
$100
100USD
USD 100
100 US Dollars
$100 (US)
100 U.S. Dollars
US: $100
```
and so on.

I don't know which class is the best class to handle this scenario, but there are so many of them with such similar functionality, it's clear that it is a recurring problem:
```
{
  "@type": "schema:PropertyValue",
  "schema:name": "International Standard Book Number",
  "schema:alternateName": "ISBN",
  "schema:propertyID": "https://www.isbn.org/",
  "schema:value": "978-92-79-58538-8"
}
```
```
{
  "@type": "schema:CategoryCode",
  "schema:inCodeSet": "https://www.isbn.org/",
  "schema:codeValue": "978-92-79-58538-8",
}
```
```
{
  "@type": "schema:DefinedTerm",
  "schema:inDefinedTermSet": "https://www.isbn.org/",
  "schema:termCode": "978-92-79-58538-8",
}
```
```
{
  "@type": "ceterms:IdentifierValue",
  "ceterms:identifierType": { "en": "ISBN" },
  "ceterms:identifierValueCode": "978-92-79-58538-8"
}
```
```
{
  "@type": "ceterms:CredentialAlignmentObject",
  "ceterms:framework": "https://www.isbn.org/",
  "ceterms:frameworkName": { "en": "ISBN" },
  "ceterms:codedNotation": "978-92-79-58538-8"
}
```
and so on.

The flip side of this would be taking the approach taken by language maps, which would require establishing a set of known codes (to serve an equivalent purpose to the BCP47 language codes used in language maps) for different, well, codes, and then populating data like this:
```
{
  "isbn": "978-92-79-58538-8"
}
```
at which point you're probably better off borrowing existing properties like `schema:isbn` and using those instead.

Anyway, the short version is, if the goal is to document both the type of code and the code itself, the only way to do that which is consistent with how we've done everything else is to use some kind of object that allows you to say "this part is the code" and "this part is the type of code".  

Otherwise, I think you should use `codedNotation` - I see no practical difference in terms of implementation or the value of the data between an opaque "dumb" string like `codedNotation` and any other property that would provide the same thing.  If I write code that can attempt to parse/figure out/guess at data in a property like `altNotation`, then there's no reason not to apply that same code to the values present in `codedNotation`.

Failing that, you would need strict rules around how such a string would be encoded in order to say something like "provide the code first, followed by [some character or character sequence that is very unlikely to be a part of a code itself], followed by the code itself" - at which point you're basically reinventing JSON.

**Comment by philbarker** [comment]
Aside: @siuc-nate for your CTDL to EOCred work 

From the [schema.org model docs](https://schema.org/docs/datamodel.html#identifierBg):

> In the most complex case, there is sometimes a need to represent the type of an identifier. In this case, a PropertyValue pair ('name', 'identifier') pair can be used when a standard URI form of the identifier is unavailable. We do not currently have a recommended identifier scheme for identifier schemes, but in most cases there is a conventional short name for most identifier schemes (which should be used in lowercase form).

which suggests:
```
{
  "@type": "schema:EducationalOccupationalCredential",
  "schema:identifier": {
    "@type": "schema:PropertyValue",
    "schema:name": "ctid",
    "schema:identifier": "ce-a7f6202e-070b-462c-ab05-e5dc1d9f21f9",
  }
}
```

**Comment by siuc-nate** [comment]
@philbarker Yes, but at the same time, the description for [PropertyValue](https://schema.org/PropertyValue) calls it a "property-value" pair and the class includes a `value` property that claims to _be_ the "value of the property value node".  So it seems there is a conflict, but including the CTID in both the `identifier` and `value` fields should solve it regardless of which part of the spec a consuming system is based on.

**Comment by Lomilar** [comment]
I'd like to resist, if it comes up, the implicit or explicit mapping between schema:identifier and (ceasn:codedNotation or skos:notation) -- Formal notations are identifiers, but not all identifiers are notations, in my mind. For example, GUIDs (as imported by IMS CASE) are identifiers but aren't intended for human consumption, as codedNotation often is.

I also tend to resist the property-value pair object or any object that encodes a triple from an RDF perspective, but sadly, they have their uses based on the fact that JSON-LD resists (through no fault of its own) statementSets because of the bizzare combination of OO principles and RDF principles. Hopefully, all the property-value pair objects extend rdf:Statement -- I haven't checked into it.

**Comment by stuartasutton** [comment]
Even when a codedNotation is not directly readable by humans, it is ALWAYS subject to parsing based on some underlying scheme known to someone (and not necessarily a consuming system).

Agree that this is far from “identifier” which frequently serves is mission of identification while remaining semantically opaque.

**Comment by Lomilar** [comment]
I'm currently for ceasn:altIdentifier being defined as "any additional identifier", however, it would not map cleanly to https://schema.org/identifier:

`The identifier property represents any kind of identifier for any kind of Thing, such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links.`

https://schema.org/identifier combines the intent of ceasn:codedNotation, ceasn:identifier, and the above proposed ceasn:altIdentifier. While I can separate URLs from non-URLs, it is more difficult to separate human interperable identifiers in a notation from other machine identifiers.

**Comment by siuc-nate** [comment]
Based on [Phil's post from April](https://github.com/CredentialEngine/Schema-Development/issues/599#issuecomment-487672415) and the fact that we're already using schema:value in schema:QuantitativeValue, I think it makes sense to go with:

```
"ceterms:altIdentifier": {
  
}
```

**Comment by stuartasutton** [comment]
Nate, don't you mean ceasn:altIdentifier?

**Comment by siuc-nate** [comment]
Yes, good catch - I have updated the example.

**Comment by siuc-nate** [comment]
I think this is something we should consider in tandem with #666 since it would be applicable in both CTDL and CTDL-ASN.

**Comment by siuc-nate** [comment]
This issue has been superseded by #715. Go there for the resolution.
