### ISSUE TITLE
Pathways Property to Reference Progression Models

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#622]
asn:hasProgressionModel (domain: ceterms:Pathway; range:ProgressionModel/skos:ConceptScheme)
asn:hasProgressionLevel (domain: ceterms:PathwayComponent; skos:Concept)
asn:ProgressionModel

**Comment by siuc-nate** [comment]
Is there a semantically-significant distinction between a "Progression Model" (as a class) and a Concept Scheme (as a class) that wouldn't also apply to any other use of a concept scheme?  For instance, we don't have an "Organization Type Model" class or an "Audience Level Model" class despite those being some unique and important uses of Concept Schemes.  

In other words, what would be the justification for creating a class here versus just using Concept Scheme as-is and leaving it to the propert(y/ies) to give it its importance/context/relevance/intended use/function/etc. (as we do in other cases)?

**Comment by stuartasutton** [comment]
Nate, this is just an extension of our frequent conversation between use of class and use of a property to identify type.  The reason we come back to this over and over again is because it is not a matter (necessarily or always) of the right or wrong way of model something.  Over time, I've come to value being able to pull together important "things" by their explicit classes.  Searching and finding something via a type property gathers stuff up but not by class.  If I'm working across a significant graph space and want to pull together progression models, what property can I assume defines these "types" in a huge array of subgraphs? I have absolutely no semantic way of knowing!  Now, if there is a class named "ProgressionModel" and people have used it to describe KOS's describing these progressions, there is no guessing about how to search.

Now does something have to have dual classes (e.g., like I suggest above for ProgressionModel/ConceptScheme). No. It would probably have been better for me to have defined ProgressionModel as a subclass of ConceptScheme. I make it an explicit subclass because I consider these models of progressions to be significant, cross-application frameworks in our domain of interest and of high interest as a whole. Many concept schemes are not of such cross-cutting interest. When is this the case? Making that decisions is the art of it...no bright right/wrong lines.

Some of this for me stems from my background in knowledge management and the pre-history of SKOS as a means to machine encode for the Web "knowledge organization systems" (KASs) such as thesauri, taxonomies, classifications, (flat) lists etc.

**Comment by siuc-nate** [comment]
The terms for this proposal need to be defined.

**Comment by stuartasutton** [comment]
ASN labels it hasProgressionModel and defines it as "Reference to a specific point in a progression model."

**Comment by siuc-nate** [comment]
What about the Progression Model class itself?

**Comment by stuartasutton** [comment]
ASN has both terms defined. Are we using the ASN namespace or recreating in a ceterms namespace?

**Comment by stuartasutton** [comment]
They attach to rubrics handled in ASN namespace and to Pathways in the ceterms namespace.

**Comment by siuc-nate** [comment]
We should use the existing stuff if it's available.  I'm looking for a formal proposal write-up of whatever needs to be added to the schema management system for documentation/reference/etc purposes, e.g.

**Add:**
> **URI:** asn:hasProgressionModel
> **Label:** Has Progression Model
> **Definition:** Reference to a specific point in a progression model.
> **Domain:** TBD
> **Range:** asn:ProgressionModel

**Comment by stuartasutton** [comment]
**Add:**

> **URI:** asn:ProgressionModel
> **Label:** Progression Model
> **Definition:** Model of identifiable points along a developmental progression including increasing levels of competence, achievement or temporal position (e.g., "Second Quarter").

> **URI:** asn:hasProgressionModel
> **Label:** Has Progression Model
> **Definition:** Reference to a specific point in a progression model.
> **Domain:** asn:Rubric, ceterms:Pathway, ceterms:CompetencyFramework
> **Range:** asn:ProgressionModel

> **URI:** asn:hasProgressionLevel
> **Label:** Has Progression Level
> **Definition:** Reference to a specific point in a progression model.
> **Domain:** asn:CriterionLevel, ceterms:PathwayComponent, ceterms:Competency
> **Range:** skos:Concept

**Comment by siuc-nate** [comment]
The second term is confusing - are you referencing the entire model or just a point in it?

**Comment by stuartasutton** [comment]
:-) The second property (hasProgressionModel) Should be "Reference to a specific progression model".

**Comment by siuc-nate** [comment]
So are asn:hasProgressionModel and asn:hasProgressionLevel roughly comparable to (and I suppose more technically, subproperties of) ceterms:framework and ceterms:targetNode, respectively?

What would an example look like that uses all three terms?

**Comment by stuartasutton** [comment]
See example of Progression Model here: http://standards.asn.desire2learn.com/rubric.html#pm. One example would be a competency framework that references a progression model (has:ProgressionModel) encoded as a skos:ConceptScheme and competencies in that framework could reference specific concepts in that model (hasProgressionLevel).

**Comment by siuc-nate** [comment]
**Add:**

> **URI:** asn:ProgressionModel
> **Label:** Progression Model
> **Definition:** Model of identifiable points along a developmental progression including increasing levels of competence, achievement or temporal position (e.g., "Second Quarter").

> **URI:** asn:hasProgressionModel
> **Label:** Has Progression Model
> **Definition:** Reference to a specific point in a progression model.
> **Domain:** asn:Rubric, ceterms:Pathway, ceterms:CompetencyFramework
> **Range:** asn:ProgressionModel

> **URI:** asn:hasProgressionLevel
> **Label:** Has Progression Level
> **Definition:** Reference to a specific point in a progression model.
> **Domain:** asn:CriterionLevel, ceterms:PathwayComponent, ceterms:Competency
> **Range:** skos:Concept

**Comment by stuartasutton** [comment]
The definition of hasProgressionModel is not accurate. It is “Reference to a progression model used.”

**Comment by siuc-nate** [comment]
Updated.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.
