### ISSUE TITLE
Work Role Class

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#623]
Finalize Work Role.

**Comment by stuartasutton** [comment]
To launch a discussion:

PROPOSAL:

>**URL:** https://purl.org/ctdl/terms/WorkRole
>
>**DEFINITION:** Entity that details a grouping of attributes required to perform a work role in the form of knowledge, skills, and abilities and tasks performed in that role.
>
>**COMMENT:** A job may be defined by a set of assigned work roles; i.e. a bundling of work associated knowledge, skills, and abilities and tasks performed

**Comment by siuc-nate** [comment]
We also need to define the properties for the class.  I propose:

- Name
- Description
- Comment
- Has Task

Has Task:
> **URI:** ceterms:hasTask
> **Label:** Has Task
> **Definition:** A task associated with this resource.
> **Domain:** ceterms:WorkRole
> **Range:** ceterms:Task

**Comment by siuc-nate** [comment]
Wouldn't the KSAs be attached to the tasks, as they are in other uses (e.g. Navy)?

**Comment by stuartasutton** [comment]
Nate, in one of your figures, you reconciled this so that both instances were accommodated. The cybersecurity model is:

Job (not in the cybersecurity framework)
     Work Role
           Knowledge
           Skills
           Abilities
           Tasks

You are suggesting (correct?):

Job 
     Work Role
           Task
                 Knowledge
                 Skills
                Abilities

What if a framework does not define tasks? Would that be:

Job
     Work Role
          Knowledge
          Skills
          Abilities

I'm game with any (all) of the above that frames Work Role in terms of Knowledge, Skills, Abilities, Tasks as long as the latter four and hang somehow off Work Role.

**Comment by siuc-nate** [comment]
I am in the process of redeveloping the navy schema to more closely align to current discussion of how occupations (#644), jobs, and work roles should work.

**Comment by siuc-nate** [comment]
See #701
