### ISSUE TITLE
Occupation Class

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#644]
Credential Engine is supporting state ETPL (approved training programs lists).  These lists will include occupations for which the program prepares.  However, the profile of the occupation is desired rather than just references to occupations.  A profile can include competencies.  This mirrors the Navy model.

**Comment by stuartasutton** [comment]
??
Occupation
      [WorkRole]
              Knowledge
              Skill
              Ability
              Task...

**Comment by siuc-nate** [comment]
The https://credreg.net/ctdl/terms#occupationType points to a https://credreg.net/ctdl/terms#OccupationClassification which is a superclass meant to cover any "thing" that represents an occupation (e.g. a reference to a SOC code).

I need more information.  Are we talking about:
- An **instance** of a job (aka "job posting") (as in, "here is a position for x number of people at y company as of z date")
- A **class** of a job (as in, x type of job generally has y tasks and z responsibilities)

An ONET job profile contains references to competencies and other things - do they intend to provide their own job profiles instead of referencing existing ONET profiles?  What about alignments between the two?

**Comment by siuc-nate** [comment]
Also, is this specifically Illinois/ProPath related or something for any state?

**Comment by stuartasutton** [comment]
@siuc-nate , Jeanne says "state ETPL (approved training programs lists)" which means any/all states.

**Comment by siuc-nate** [comment]
I assume so, but I wanted to be sure.

**Comment by stuartasutton** [comment]
Over time, the aperature of credential in the context of Credential Engine will broaden. While competencies were present from CE's beginning, a competency framework entity as we now see was not in view. Neither were concept schemes or rubrics. Pathway's were within early vision but not as the current entity. These 'collateral entities' will likely continue to grow as the credential lens broadens its aperature. I'll lay a bet on jobs...

**Comment by siuc-nate** [comment]
We just need to be careful as we work through that to only expand the scope based on where we _should_ rather than where we _can_.

**Comment by stuartasutton** [comment]
@siuc-nate, at https://github.com/CredentialEngine/Schema-Development/issues/644#issuecomment-565087990 you ask whether this is intended for a job posting or what JDX calls a job description (basically a class). My sense is that it is the latter.

**Comment by siuc-nate** [comment]
I agree that it makes a lot more sense to document a class of occupation rather than an instance of occupation, especially given the permanent/archival nature of the Registry.

There is now a google drive folder with related documentation:
https://drive.google.com/drive/folders/1IxYFi3Hkj1xy0uWApVp0sGSNy0eWQ1Id

I should also note that, in the Navy project, we do not have _any_ data for the Work Roles beyond their name and what they are connected to - they could be reimplemented as a concept scheme without breaking anything.

**Comment by siuc-nate** [comment]
See #701
