### ISSUE TITLE
ETPL approval indicator 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#645]
Each state maintains WIOA-approved program lists.  Federal and state policies determine how programs qualify to be included with a state's list.  At this time, these lists are state by state and programs may be approved either statewide or regionally.  Regions are Local Workforce Innovation Areas.  It is very likely that some of the programs are approved state by state are national credentials that should not be duplicated in the Registry.   In order for states to differentiate the programs that are WIOA-approved an indicator is needed. Other properties may be needed as well.  This may require a task group to be convened.

**Comment by siuc-nate** [comment]
**Scenario 1:**
Direct property relationships.  For example, the state of New Jersey (a QA organization) would reference a number of credentials via the ceterms:etplApproves property. Those credentials would point back to New Jersey via the ceterms:etplApprovedBy property.
- ceterms:etplApproves
  - Resource that is approved to be on an Eligible Training Provider List related to this organization.
  - Domain: Organization
  - Range: Credential, AssessmentProfile, LearningOpportunityProfile

- ceterms:etplApprovedBy
  - Domain: Credential, AssessmentProfile, LearningOpportunityProfile
  - Range: Organization
  - Referenced organization is related to an Eligible Training Provider List that includes this resource.

**Scenario 2:**
Resource Set object.  For example, the state of New Jersey (a QA organization) would reference a Resource Set for each of its ETPLs. These Resource Sets would, in turn, reference the information relevant to that ETPL, such as LWIA, demand occupation, and the list of applicable credentials.
- ceterms:ResourceSet
  - Collection of resources related for some purpose.
  - Properties:
    - Name, Description, Subject Webpage, Target Credential, Target Learning Opportunity, Target Assessment, Target Competency, Instrument, Main Jurisdiction, Industry Type, Occupation Type, Instructional Program Type, Resource Set Type

- ceterms:hasResourceSet
  - Resource Set maintained by this organization.
  - Domain: Organization
  - Range: ResourceSet

- ceterms:resourceSetType
  - Type of Resource Set; select from an existing enumeration of such types.
  - Domain: ResourceSet
  - Range: CredentialAlignmentObject

**Comment by siuc-nate** [comment]
I think I've changed my mind after seeing how much of a behemoth solution 2 became - I think solution 3 gives us all of the benefits we're looking for without all the extra overhead, dev time, complexity, etc.

The main benefit of solution 3 over solution 1 in my opinion is having that object in the middle (the QA Credential) that allows an organization to have multiple ETPLs.  Since QA Credential already facilitiates connecting to a bunch of other things (including WIOAs via Place, boards for those WIOAs via approvedBy, branching requirements for being on the ETPL, financial assistance info, etc.) I think it makes more sense to use it instead of creating a new object that risks ballooning into a Credential-sized thing.  

To me this outweighs the reusability features of solution 2, which would be "nice to have" but for which we don't have an actual pressing need.

So my vote is for solution 3. I think it gets us the simplicity of solution 1 with the flexibility of solution 2 (moreso in fact) while being very simple to understand and implement (and we get to leverage having ETPL-specific properties we can define more closely).

It also dodges the need to create a Resource Set concept scheme.

**Comment by philbarker** [comment]
@siuc-nate +1 for option 3. 

Are the arrows for isEPTLMemberOf pointing in the wrong direction?

**Comment by siuc-nate** [comment]
@philbarker Oops - good catch.  I fixed the image.

**Comment by siuc-nate** [comment]
Replaced by #696
