### ISSUE TITLE
Credential Pass Rates

### ISSUE THREAD

**Issue by erafal10** [CredentialEngine/Schema-Development#647]
Several partners have asked about how to include information about pass rates for credentials, specifically certification and licensure. 

Right now, this information can be found in a number of places, such as: https://www.umaryland.edu/iespa/institutional-effectiveness/professional-licensing-exam-pass-rates/

https://www.in.gov/che/files/NursingLicenseExamPassRates.pdf

I don't believe there's a good way to publish that information to the Registry currently.

@siuc-nate @stuartasutton @jeannekitchens

**Comment by jeannekitchens** [comment]
@erafal10 @stuartasutton @siuc-nate This is part of Credential Holders Profile. This will need to be a task group just as we formed task groups for pathways and employment and earnings.  We'll need information such as the examples provided so thanks for that. It has taken approx. 6 months per task group.  This could be shorter due to qualitative data already being substantial thanks to the employment and earnings task group.  However, it is dependent upon how soon we can organize and convene a group and how much we find in the research.

**Comment by stuartasutton** [comment]
While we'll need to look at many more examples, the few examples referenced are *technically* in the form of a spreadsheet; i.e., rubric-like in technical form. While the properties of the ASN Rubric specification we are looking at for rubrics aren't defined and labeled to suit this context (see http://standards.asn.desire2learn.com/rubric.html), it will be interesting to determine the level of accommodation. Also, perhaps a look at W3C's CSV on the web (https://www.w3.org/TR/tabular-data-primer/#json-ld) that can be transformed into RDF and remit as json-ld.

Only more examples (recurring use pattern) will tell if this is technically a potentially approach.

**Comment by stuartasutton** [comment]
We need to look at the intersection here between HoldersProfile and AssessmentProfile.

**Comment by siuc-nate** [comment]
This has been handled. See #751
