### ISSUE TITLE
Propath has several potential additions for the Audience concept scheme. We need guidelines for additions to Audience concepts.

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#648]
@stuartasutton 
The propath project has identified the following as additions to the audience concept scheme:

audience:DisplacedHomemaker
audience:LowIncome
audience:Disability
audience:ExOffender
audience:Homeless
audience:RunawayYouth
audience:FosterCareRecipient
audience:FosterCareProvider
audience:EnglishLanguageLearner
audience:LowLiteracy
audience:FacingCulturalBarriers
audience:MigrantSeasonalFarmworker
audience:PublicAssistanceRecipient
audience:SingleParent
audience:LongTermUnemployed

The above could be viewed as the audience for a program. The context is really clientele for a program. 
In anticipation of this and other projects proposing additions to the concept scheme, is some sort of different approach needed?
For example:
- a means to categorize the audience?
-- the financial assistance scheme has some example of this 
- grouping of

**Comment by siuc-nate** [comment]
@stuartasutton Sort of - They have candidate/placeholder definitions that were derived from fuller legal definitions where I could find them.  Those, and notes about those, are in the Concepts tab here:
https://docs.google.com/spreadsheets/d/1L213QzmTtOWdmAHeFopPMsrOv-Tj5kw5H6FCPCvmZO8/edit#gid=1547473779

Jeanne pointed out that we should look for existing definitions in CEDS - that's probably a good starting point.  The definitions need review regardless, since I am not an expert and I assume those terms have particular legal meanings we should be aware of.

>The context is really clientele for a program.

I have attempted to capture that via the property that points to the concept scheme rather than in the concept scheme itself, so that those concepts can be reused for other purposes. (see propath:audiencePriorityType in the Properties tab of the above spreadsheet).

The question we're trying to solve is, in the context of ProPath (for instance, an application dealing with ProPath-related data), does it make sense to have the above concepts show up in the same concept scheme as the existing CTDL Audience concepts? We're not asking about adding them to vanilla CTDL.

To me, even though those are _technically_ types of audience, they seem a lot more specific than the broad concepts already in the Audience concept scheme, and collectively all focus on various types of major problem a person may face (generally with some kind of explicit or implicit economic aspect, which is not found in the other Audience concepts) and it makes sense to group them together somehow.  

I'm not particularly concerned with whether the grouping is via a concept scheme or a concept that the new terms are all subconcepts of; I think either one works from the standpoint of developing applications that will use these terms.

Thinking about it another way: We distinguish between "Audience" and "Audience Level" even though "Beginner" is as much a descriptor of a person as "Member" is - I think it makes sense to distinguish between the new terms and our current Audience vocabulary as well.

Perhaps either a concept scheme like "Audience Disadvantage", "Audience Difficulty", "Audience Challenge", "Audience Struggle" or "Audience Economics" - something that captures what the concepts are trying to collectively discuss without coming across as insensitive.  Adding them as a separate concept scheme would probably make it easier to document the Audience concept scheme from both the perspective of vanilla CTDL and ProPath.

Having them grouped together (preferably as a separate concept scheme) makes it a lot easier to grab all of them when you're doing queries or generating data as well, if for whatever reason you needed to separate them.

```
SELECT * WHERE something[skos:inScheme] = "propath:AudienceHardship"
```
or even
```
SELECT * WHERE something[skos:broader] = "audience:Disadvantaged"
```
are **vastly** preferable (and resilient to additions/changes to terms within that group) compared to
```
SELECT * WHERE something = "audience:DisplacedHomemaker" OR something = "audience:Disability" OR something = "audience:MigrantSeasonalFarmworker" OR (etc...)
```

One more thing to consider: putting these terms in their own concept scheme means that concept scheme can fall under the umbrella (and therefore the policy, the stakeholders, the schema update schedule, etc.) of the ProPath schema rather than having them piggybacked onto CTDL.  I think that's something important to think about as well.

One more, possibly radical solution: Create a new concept scheme in ProPath that houses the new concepts, and then borrow the existing audience terms from CTDL's Audience scheme, rather than borrowing the Audience scheme itself.  This would have the following benefits:
- The concept scheme and its concepts would exist in ProPath and be subject to all of the policy, update schedule, etc. stuff that the rest of ProPath is
- The documentation could still be generated that shows these terms being in their own concept scheme, without confusion about "why are they in Audience here but not over here"
- The more general terms found in Audience would be grouped by default since their URIs would all be prefixed with `ceterms` while the new concepts would be prefixed with something else, allowing them all to be displayed and considered as one flat list while also being easily separable for querying/interface purposes (the implementer would have the option to separate them or show them all together)
- If we ever change our minds later, we can just remove the "skos:inScheme" triple from the Audience concepts that points to the new concept scheme without breaking any published data

Okay, I think i typed myself into it - I want to push for that last idea.

**Comment by jeannekitchens** [comment]
See CEDS https://ceds.ed.gov/CEDSElementDetails.aspx?TermId=20969.
See Illinois WIOA Policy Glossary https://apps.illinoisworknet.com/WIOAPolicy/Policy/Glossary/A
US Dept. Of Labor TEGL 19-16 Attachment III https://wdr.doleta.gov/directives/attach/TEGL/TEGL_19-16_Attachment_III.pdf and https://www.dol.gov/agencies/eta/advisories/training-and-employment-guidance-letter-no-19-16

audience:DisplacedHomemaker
audience:LowIncome
audience:Disability
audience:ExOffender
audience:Homeless
audience:RunawayYouth
audience:FosterCareRecipient
audience:FosterCareProvider
audience:EnglishLanguageLearner
audience:LowLiteracy
audience:FacingCulturalBarriers
audience:MigrantSeasonalFarmworker
audience:PublicAssistanceRecipient
audience:SingleParent
audience:LongTermUnemployed

**Comment by jeannekitchens** [comment]
Additional audience types were added in May.  Closing this and we can re-review if additional updates are needed.
