### ISSUE TITLE
Occupation Specialty

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#704]
The concept of a "specialty" was in the original Education/Training to Jobs domain sketches, but we couldn't distinguish it as a class from Occupation. It's just an more specialized occupation. If the Occupation-->Specialty relationship is important to us we need a "hasSpecialty" property, domain and range Occupation.

Nate suggests by email that hasChild/isChildOf may be suitable existing property.

**Comment by stuartasutton** [comment]
I prefer `hasSpecialty` to `hasChild'. I would also support making `hasSpecialty` a subproperty of `hasChild`. While there is something to be said for holding down the number of CTDL properties, there is something **more important** to be said for defining subproperties with more specific semantics where it is useful to do so. I think this  is one of those cases. I'd further support declaring both `hasSpecialty` and `isSpecialtyOf` as owl:inverseOf` properties.

**Comment by siuc-nate** [comment]
I'm not strongly tied to the idea of using hasChild for this, so that's fine.

I am, however, concerned that this further blurs the line between an occupation and an occupation classification system (i.e. concept scheme).  With the properties proposed here, you could conceptualize (and reconstruct) ONET using just the Occupation class, no concept scheme to provide the "structure" or "classification" as we've previously discussed.

Though that might be more correct, as it turns ONET, ESCO, etc. into large trees of Occupation class instances rather than concept schemes that are somewhat confusingly related to Occupation classes.

**Comment by jeannekitchens** [comment]
@philbarker  can you provide definitions for:

ceterms:hasSpeciality
ceterns:isSpecialtyOf

I'll add the draft terms to the [model ](https://app.diagrams.net/#G1fpXoRRwQrFrz7LZ-nf8Bm-N8zGfXt3oZ)and to the [draft terms proposal](https://docs.google.com/spreadsheets/d/1SMsoT2yZ7jgNSdr-okd90Rg614r133ELamesgOMUDPQ/edit#gid=911562452) in the Occupation tab.

**Comment by siuc-nate** [comment]
Merged into #701:
https://github.com/CredentialEngine/Schema-Development/issues/701#issuecomment-680200005
