### ISSUE TITLE
Can the new high-level credit unit types of: creditUnit:TimeBasedCredit and creditUnit:TypeBasedCredit be published

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#726]
For credit units, there are the new high-level credit unit types creditUnit:TimeBasedCredit and creditUnit:TypeBasedCredit.
These were stated: "to serve as categories for the other types". For example:

> URI: creditUnit:DualCredit
> Label: Dual Credit
> Definition: Credit that is applicable to two different educational levels.
> Broader: creditUnit:TypeBasedCredit
> In Scheme: ceterms:CreditUnit
> 

Can these concepts actually be used for publishing, or are they treated like a category and should NOT be allowed as a published term?
If not, the Assistant API will be updated to reject attempts to publish creditUnit with either of these concepts.

Credit defintions
https://docs.google.com/document/d/1LC6_GbKdYWYwLoGtYAUahRxWdSJ2By815Br_-iQ1mGw/edit#heading=h.pcn8ifkubcfx

**Comment by siuc-nate** [comment]
I can see it being useful to allow these for cases where none of the more specific unit types are applicable but one of the higher level ones is - however, it may also lead to questions about whether or not you should always pick one of the higher level items if/when you pick one of the lower level ones.  I don't have a strong opinion either way.  

I suppose that as long as we allow for other credit unit types to be referenced (either as bnodes or by URI), it shouldn't be a problem to consider these to be categories rather than options that can be chosen.  But my mind could be changed on this.

**Comment by jeannekitchens** [comment]
Decision was made to support publishing either CreditUnit:typeBasedCredit and timeBasedCredit to the Registry.
