### ISSUE TITLE
A valueProfile can have multiple creditUnitTypes with one Value. Will consumers understand how to interpret potential values?

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#727]
The ValueProfile defines CreditUnitType as a list, and Value as single. 
If a ValueProfile is published with credit units of: "Degree Credit" and "Semester Hour", and a Value of 6, is it fairly universally understood how to interpret the latter?
Or is some guidance required for data like the latter?

**Comment by mparsons-ce** [comment]
@siuc-nate The key point/concern is for understanding by consumers, or non-CE staff!
You had brought up the example using "Degree Credit" and "Semester Hour".
How should a ValueProfile with the latter credit units and a Value of 6 be interpretted?

**Comment by siuc-nate** [comment]
I would suggest reading it as 6 degree credits measured in semester hours (as opposed to degree credits measured in clock hours or quarter hours or some other means). The concepts are describing attributes of the credit, but there is no case where you would interpret that as 6 degree credits and 6 semester hours (total of 12) unless there were two separate ValueProfiles where each one had just one of those unit types selected.

We have a similar case with credit **level** type where "professional" can be combined with one or more other types to refine the level type without needing to have a distinct concept for every possible combination.

I would also compare organization type, where an organization can simultaneously be described as `orgType:PrimarilyOnline`, `orgType:TrainingProvider`, and `orgType:Business`.  None of the other properties of organization would be considered 3 times simply because multiple values were chosen for type.  I think the same applies for unit type.

If I have 6 `fruit:orange`s I can describe the `aspect:flavorType` as `flavor:sweet` and `flavor:tangy` without interpreting the situation as me having 12 oranges where half of them are sweet and the other half are tangy.  If I wanted to do that, I'd just use two FruitProfiles.

**Comment by jeannekitchens** [comment]
The CTDL Handbook and API Publishing Handbook.  There's no changes to the CTDL.
