### ISSUE TITLE
Add a property to capture sub-regions

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#739]
Per our 11/6/2020 meeting:

The schema.org https://schema.org/PostalAddress (and, by extension, our https://credreg.net/ctdl/terms/Place class) lacks a property for capturing geographical divisions that sit between addressRegion and addressLocality.  In the US, these would be counties.

The only relevant documentation I could find that grapples with this problem is [this schema.org issue](https://github.com/schemaorg/schemaorg/issues/1848) which stalled out due to inactivity.

We should add a property to enable capturing counties and their equivalents in other countries.

Proposal:

**Add:**
> **URI:** ceterms:addressSubRegion
> **Label:** Address Sub-Region
> **Definition:** Named area or division within a region, such as a county in the U.S. or Canada.
> **Domain:** ceterms:Place, ceterms:PostalAddress
> **Range:** rdf:langString

**Comment by stuartasutton** [comment]
Perhaps Phil could provide a UK equivalent for the "such as" phrase.

**Comment by philbarker** [comment]
There's a side issue with schema:Address in the UK because UK Addresses are not based on geographic or givernmental administrative entities (see [my comment](https://github.com/schemaorg/schemaorg/issues/1848#issuecomment-366645494) on that issue). 

That said, UK administrative divisions include: "county", "unitary authority", "council area" and "combined authority", and these fit quite nicely into Address--region. Where we have an issue is the next level up, with what are called (confusingly) the English Regions ( "East of England", "North East England") & UK Consituent Countries (Scotland, Northern Ireland, Wales, England).

Enumerating levels of hierarchies always ends up messy, take a look at [what happened to](https://en.wikipedia.org/wiki/Taxonomic_rank#All_ranks) kingdom>phylum>class>order>family>genus>species that you may have learnt at school.

**Comment by siuc-nate** [comment]
For what it's worth, we don't necessarily need to frame this in the context of addresses, at least not for the US use case (and presumably for other countries as well given there's no schema.org property for it).  

What brought this on was needing to reference, by name, a US county (in the context of something like a search, e.g. "show me all the credentials I can pursue in this county") and not having any property with which to do so.  It would also apply in the context of https://credreg.net/ctdl/terms/JurisdictionProfile which also uses Place to define itself (e.g. "this credential is valid in this county").

**Comment by philbarker** [comment]
@siuc-nate to meet that use case do you need any more specific type than `Place`? I mean, in order to find everything you need to know about Norfolk, does it matter that it is a County and a County is bigger than a Parish but smaller than a Region? Does `schema:containsPlace` and `schema:containedInPlace` tell you enough?
```
{ 
  "@context": {
    "@vocab": "http://schema.org/",
    "@base": "https://www.wikidata.org/entity/"
  },
  "@type": "Place",
  "@id": "Q23109",
  "name": "Norfolk",
  "containedInPlace": {
      "@type": "Place",
      "@id": "Q580631",
      "name": "East Anglia"
   },
  "containsPlace": {
       "@type": "Place",
       "@id": "Q629427",
       "name" :"Caister-on-Sea"
  }
}
```

**Comment by jeannekitchens** [comment]
We're adding identifier via #752 and closing this.
