### ISSUE TITLE
Are Employers CredentialOrganizations?

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#765]
We have Job--[offeredBy]->CredentialOrganization. 

Do employers meet criteria of "playing one or more key roles in the lifecycle of a credential" or should schema:Organization be range?

**Comment by philbarker** [comment]
As discussed in the call of 30 Mar: no, employers in general are not CredentialOrganizations. We should create a new class `ceterms:Organization`, as a superclass of `ceterms:CredentialOrganization` and `ceterms:QACredentialOrganization` and equivalentClass to `schema:Organization`;  `ceterms:Organization` should be added to the range of `ceterms:offeredBy`.

Proposal:

Create:

> URI: ceterms:Organization
> Label: Organization
> Definition: An entity such as an association, company, corporation, club, co-operative, labor union etc.
> Usage Note: For organizations that are involved in the lifecycle of a credential or Quality Assurance use the more specific ceterm:CredentialOrganization or ceterms:QACredentialOrganization.
> Properties: ceterms:name, ceterms:description, ceterms:address, ceterms:alternateName, ceterms:ctid, ceterms:department, ceterms:email, ceterms:duns, ceterms:fein, ceterms:industryType, ceterms:isicV4, ceterms:leiCode, ceterms:naics, ceterms:parentOrganization, ceterms:sameAs, ceterms:socialMedia, ceterms:subjectWebpage, ceterms:subOrganization

Add:

> Subject: ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> Predicate: rdfs:subClassOf
> Object: ceterms:Organization

Add:

> Subject: ceterms:offeredBy
> Predicate:  schema:rangeIncludes
> Object: ceterms:Organization

Add:

> Subject: ceterms:Organization
> Predicate: owl:equivalentClass
> Object: schema:Organization

**Comment by siuc-nate** [comment]
@jeannekitchens Do you mean [owns](http://credreg.net/ctdl/terms/owns) and [offers](http://credreg.net/ctdl/terms/offers)? Those would be the properties we would put on a ceterms:Organization class.

**Comment by stuartasutton** [comment]
While I agree with the proposal to the extent that it creates an Organization class and appropriate new domain designations, I still think we need an Employer subclass to Organization. The reason is that we have circled around Employer as a class now for years. Here we're have looking at employers in the context of Jobs. In the past we've looked at them in terms of soft sorts for of quality assurance like preferring, endorsing of credentials etc. etc.. I'm also not fond of a data solution to differentiating using a type property and a controlled vocabulary as suggested yesterday--i.e., I prefer an ontological solution as opposed to a data solution to differentiating things in the world. We have singled out two types of organizations as particular significant in our domain--CredentialOrganization and QACredentialOrganization. I'm suggesting that Employer is a third.

**Comment by siuc-nate** [comment]
What would be the significant/real differentiating factor that separates an Employer from an Organization at the class level, in a way that can be understood by our partners (publishers and consumers alike)? 

I doubt we would even need to add another type to the OrganizationType vocabulary, as any Employer is likely to be at least one of the types already listed (e.g. orgType:Business).

**Comment by philbarker** [comment]
@siuc-nate an Employer would offer Jobs,  CredentialOrganization would offer Credentials or a QACredentialOrganization would  offer QA functions regarding credentials. (And yes, an organization might be all three, that's reality.)

I think Organization (if still needed) would become a class existing only as a superclass to group Employer, CredentialOrganization and QACredentialOrganization and show they were related to schema.org/Organization, much the same as the Credential superclass.

**Comment by siuc-nate** [comment]
If all we need is a superclass that never actually gets published or used, then we already have Agent for that. 

The problem exists where an organization does more than one thing and doesn't fit neatly into a single subclass of organization (hence the need for the Organization class).  But if you have an all-consuming Organization class, I don't think we need any other subclasses of it unless there is a very good reason (e.g. it does something meaningful that an Organization does not).  We already have the OrganizationType vocabulary for providing that soft-subclassing (with the added benefit of it allowing for multiple selections).

I'll put it this way: If I were designing CTDL from scratch today, I would have one Organization class with no subclasses at all.

If we're going to add an Employer subclass, then we need to at least give thought to other subclasses of organization we might realistically need and consider whether expanding the OrganizationType vocabulary and using a more generic Organization class would be a better solution, because I have a feeling that it would be.

Adding more (identical) classes adds unnecessary overhead when dealing with properties and the like, as we have already seen with the 20+ subclasses of Credential.

**Comment by philbarker** [comment]
> If all we need is a superclass that never actually gets published or used, then we already have Agent for that.

The Employer class would be used.

> I'll put it this way: If I were designing CTDL from scratch today, I would have one Organization class with no subclasses at all.
...
> Adding more (identical) classes adds unnecessary overhead when dealing with properties and the like, as we have already seen with the 20+ subclasses of Credential.

They're not identical.

It is useful to distinguish betwen different types of things, even if you describe them with the same properties -- **especially** if you  describe them with the same properties. There is no need for another subset of schema.org, but something more expressive is useful.

**Comment by philbarker** [comment]
> I meant that in the context of figuring out whether or not we need both Organization and Employer.

Ah, that looks clear now. Sorry for the misunderstaning.

> Given that most organizations offer jobs,

I suspect that is not true, and it also makes me think that I was wrong to suggest the Organization superclass would not be used. The `ceterms:subOrganization` and `ceterms:department` would point to things that would be Organizations but not independent legal entities that could emplot people. They're important because often the employment is with a national or international employer, but the work is actually based at a local branch / department.

Other organizations that don't employ are things like clubs, and some partnerships and associations, but I'm not sure we would deal much with them.

Using a classification on a generic class (e.g. Organization Type vocabulary) is a bit of a deadend in RDF. Essentially it's just using a non-standard variation on rdf:type to point to something which is less straightforward to handle as an rdfs:Class. It affects how useful CTDL will be for other standardization efforts.

**Comment by stuartasutton** [comment]
Nate, we have been at loggerheads over this notion since day one. So, why don't we have one entity in the domain model--"Thing" (the domain of everything) and then use a type property and a concept scheme that lets us say this Thing is this type and that Thing is that type.  Run that past developers of ontologies and see how it plays.   Reread Phil's comment immediately above multiple times...particularly the the last paragraph: 
> "Using a classification on a generic class (e.g. Organization Type vocabulary) is a bit of a deadend in RDF. Essentially it's just using a non-standard variation on rdf:type to point to something which is less straightforward to handle as an rdfs:Class. It affects how useful CTDL will be for other standardization efforts."

**Comment by jeannekitchens** [comment]
- Agent
   - CredentialPerson
   - Organization (equivalent to schema:Organization)
      - CredentialOrganization
      - QACredentialOrganization
   
URI: ceterms:Organization
Label: Organization
Definition: An entity such as an association, company, corporation, club, co-operative, labor union etc.
Usage Note: Use for entities that are not a Credential Organization or a QACredential Organization.
Properties: ceterms:name, ceterms:description, ceterms:agentType, ceterms:address, ceterms:alternateName, ceterms:ctid, ceterms:department, ceterms:email, ceterms:duns, ceterms:fein, ceterms:industryType, ceterms:isicV4, ceterms:leiCode, ceterms:naics, ceterms:parentOrganization, ceterms:sameAs, ceterms:socialMedia, ceterms:subjectWebpage, ceterms:subOrganization   

[ceterm:CredentialOrganization](https://credreg.net/ctdl/terms#CredentialOrganization)
Definition: Organization that plays one or more key roles in the lifecycle of a credential.
Usage Note: For entities that are not a Credential Organization or a QACredential Organization, use ceterms:Organization  

[ceterms:QACredentialOrganization](https://credreg.net/ctdl/terms#QACredentialOrganization)
Definition: Quality assurance organization that plays one or more key roles in the lifecycle of a credential, learning program, or assessment.
Usage Note: For entities that are not a QACredenitialOrganization or a CredentialOrganization, use ceterm:Organization.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
