### ISSUE TITLE
Scheduling patterns

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#778]
It is common to generalize if scheduled learning opportunites or assessments are offered during the day, evenings, and/or weekends.  Learning opportunities could provide one or all of these options. These are generalizations not exact times for instances.  The puprose is to give people general information because many people have other activities during any given day.

Schema.org equivalent https://schema.org/timeOfDay (Pending)  - The time of day the program normally runs. For example, "evenings".  Note this is a property with EducationalOccupaionProgram.  The timeOfDay property would have been added based on use cases and community input.  Possibly facilited by Phil?

This could be a concept scheme: GeneralSchedule - generalizations of when access to learning opportunities or assessments are offered.  Comment: These are not start and end times or exact instances of an offering.  They are generalizations that help people plan around their daily activities.  Or, it could be a General Schedule property.
 
WeekendSchedule  - Learning Opportunities or Assessments accessible during weekend hours.
NightSchedule  - Learning Opportunties or Assessments accessible during evening houus
DaySchedule- Learning Opportunties or Assessments accesible during day time hours.

This is a ProPath use case.  Scroll down to Program Offerings https://apps.illinoisworknet.com/cis/wioatraining/program/3774_405

**Comment by siuc-nate** [comment]
Long ago in the planning phase for Pro Path I had come up with a "Schedule" concept scheme for this, defined as:
"Broad types of schedules for which events are typically planned."

It had many of the concepts below, though I have pruned some and tweaked a few here:
- schedule:SingleInstance
	- Single Instance 
	- Schedule is a single instance of this event.
- schedule:Weekdays
	- Weekdays
	- Schedule is typically during regular weekdays, Monday through Friday.
- schedule:Weekends
	- Weekends
	- Schedule is typically during regular weekends, Saturday and Sunday.
- schedule:Daytime
	- Daytime
	- Schedule is typically during daytime hours.
- schedule:Nighttime
	- Nighttime
	- Schedule is typically during nighttime hours.
- schedule:SpecificWeekDays
	- Specific Days
	- Schedule typically occurs on specific days of the week, often skipping one or more days in between.
	- Examples include schedules such as "monday-wednesday-friday" and "tuesday-thursday".
- schedule:Weekly
	- Weekly
	- Schedule is typically once per week.
- schedule:Monthly
	- Monthly
	- Schedule is typically once per month.
- schedule:Annually
	- Annually
	- Schedule is typically once per year.
- schedule:Summer
	- Summer
	- Schedule is typically during summer months.
- schedule:Irregular
	- Irregular
	- Schedule has no significant pattern.
- schedule:SelfPaced
	- Self-Paced
	- Schedule allows for participation at a self-determined pace, though some specific dates and deadlines may be involved.
- schedule:OpenEntryExit
	- Open Entry/Exit
	- Schedule allows for the participant to enter, participate with, and complete the resource during any period of the resource's run time.
- schedule:OnDemand
	- On-Demand
	- Schedule allows the participant to choose when the resource begins.
- schedule:EventBased
	- Event Based
	- Schedule is determined or triggered by other events, such as completion of activities, completion of the resource, events external to the resource, or other events; refer to the resource's information for details.
- schedule:FullTime
	- Full-Time
	- Schedule is considered full-time.
- schedule:PartTime
	- Part-Time
	- Schedule is considered part-time.

They were based on a combination of personal experience, [the original propath crosswalk](https://docs.google.com/spreadsheets/d/1L213QzmTtOWdmAHeFopPMsrOv-Tj5kw5H6FCPCvmZO8/edit#gid=475839920), and [the related IWDS concept scheme](https://docs.google.com/spreadsheets/d/15THHWCQZYRZpO-R9Nn-7ubUsCZOtmPiBM5-UwLa-wLo/edit#gid=269517760):
The ProPath Crosswalk includes (row 35):
- Night
- Summer
- Weekend
- Other (specify)

The IWDS concept scheme includes (rows 3-14):
- Full-Time Enrollment
- Part-Time Enrollment
- Weekend Classes
- Night Classes
- Day Classes
- Open Entry/Exit
- Other (specify)

So we probably don't need all of the terms listed in big concept scheme above, but it may make for a good starting point. The use of "typically" is intentional and meant to allow for things like events and holidays that may cause slight discrepancies to otherwise normal schedules.

**Comment by philbarker** [comment]
The request for the schema.org timeOfDay property came from Google, and was based on the data they saw on websites advertising educational programs and what they needed in order to meet user needs when building search products.  In retrospect I think they gave it a poor name as "weekend" is important but not  a time of day.

**Comment by jeannekitchens** [comment]
@philbarker good to know and they did give it a poor name but the intent makes sense.  For CTDL, this is not instance data.  This is a generalization to communicate if something is available in general in a way to help people who have other activities in their lives.   It used to be back in the day, where learning opps occured duing the day mainly during normal working hours.  Today, people need to know if the can attend at night because they work or over the weekend because they have family to take care of ect...

**Comment by jeannekitchens** [comment]
@siuc-nate thanks for pulling all of those details together.  Very thorough.

**Comment by philbarker** [comment]
schema.org has a concept scheme for the days of the week (Mon - Sun*). Should we add these to supplement or replace schedule:SpecificWeekDays ?




* or Sun - Mon if you prefer :)

**Comment by siuc-nate** [comment]
That would call into question whether or not we need:
- Weekdays
- Weekends
- SpecificWeekDays
- Weekly

I think actually providing all 7 days of the week as concepts may be a bit overly specific? The idea here is to capture _types_ of schedules, not exact schedules - I would hope we don't need to capture those, as having a certain amount of ambiguity makes it easier for people doing searches to get results. It's a fine line to walk though. And it is worth considering before we start carving these concepts into stone.

**Comment by philbarker** [comment]
Weekends/Weekdays seems as important as daytime/nighttime for someone who has a regular job and wants to know whether they can attend a course (though "evening" would be more common that nighttime in the UK -- should that be added). Likewise, if an evening course is always on Tuesdays that would be a significant factor in determining whether I could attend it.

**Comment by siuc-nate** [comment]
So are you saying we should instead have:
- SingleInstance
- Daytime
- Nighttime
- Monthly
- Annually
- Summer
- Irregular
- SelfPaced
- OpenEntryExit
- OnDemand
- EventBased
- FullTime
- PartTime
- Sunday
- Monday
- Tuesday
- Wednesday
- Thursday
- Friday
- Saturday

My worry is that being too specific will require more complex queries for people who are interested in more general data - and we don't want to include both "weekdays" and list out all of the weekdays, because then someone who wants to publish weekdays will have to determine whether or not to pick all available options, and someone searching for them will have to remember to query for all available options. I prefer to keep things simpler unless/until there is a demand for more detail.  

A schedule tightly constrained to a particular day of the week seems like an edge case to me. Does that also imply that we should list out all 12 months of the year instead of using "Monthly" and "Summer"? Someone could also be looking for classes during specific months.

We _can_ capture that kind of granularity - the question is, _should_ we? In other words, do the presumably rarer cases where it's useful to be that specific make it worth the added effort on the parts of publishers/consumers for the cases where that kind of specificity isn't needed (or isn't available in the source data)?

**Comment by siuc-nate** [comment]
Having said that, I suppose it may be easier to intuit what one should publish/query for if we do provide specific days of the week, rather than needing to interpret the definitions for the various groupings in the original suggestion.  And if there ever is a case in the future where we need to come back later and add those specific days of the week to the concept scheme, then we'll end up in precisely the "two layers of precision" problem I outlined above.  In that sense, it may be more future-proof to just bite the bullet now and add all of the week days in place of the various groupings currently in the suggestion.

That does still beg the question of whether we should include the 12 months of the year as well, instead of the month-related groupings.  It doesn't seem like it makes much sense to do one and not the other.

**Comment by siuc-nate** [comment]
I've been trying to work out a list of vocabulary terms that permits listing specific days of the week, specific months of the year, but also allows for cases where that data may not be known (or cared about).  I keep running into problems like "I know it's a weekly course, but it could be more than once per week, but it's offered during different sets of specific days in different instances" and "It's a monthly course but it could be more than once per month, but not often enough to be considered weekly"

Then there's also things like "every other week" and "every other month" that could come up too.  

I'm starting to suspect that the problem lies in trying to use the same concept scheme to describe two different kinds of data: one being the original intent, the general "type" of schedule; the other being a _specific_ schedule for a given instance of a course (ie the difference between a "schedule:SpecificWeekDays" course and "this particular offering is exactly monday-wednesday-friday"). Should we have some other mechanism for describing **actual** schedules as opposed to **types** of schedules? It's difficult to tell exactly where one becomes the other but I think that's what I'm grappling with.

**Comment by siuc-nate** [comment]
The deeper into this I dig, the more it starts to look like we would need something like schema:CourseInstance or (if we wanted something applicable to Assessments and such) schema:Offer. That kind of instance data may be beyond what we want to capture in the Registry, though, since it's pretty far from just being abstract at that point.

To avoid treading too far into instance territory, I would probably revise the list of schedule types to something like this:
- schedule:SingleInstance
	- Single Instance 
	- Schedule is a single instance of this event.
- schedule:Daytime
	- Daytime
	- Schedule is typically during daytime hours.
- schedule:Nighttime
	- Nighttime
	- Schedule is typically during nighttime hours.
- schedule:Annually
	- Annually
	- Schedule is on an annual basis, typically occurring once per year.
- schedule:Monthly
	- Monthly
	- Schedule is on a monthly basis, typically occurring once or more per month.
- schedule:Weekdays
	- Weekdays
	- Schedule is typically during regular weekdays, Monday through Friday, consecutively or non-consecutively.
- schedule:Weekends
	- Weekends
	- Schedule is typically during regular weekends, Saturday and/or Sunday.
- schedule:Irregular
	- Irregular
	- Schedule has no significant pattern.
- schedule:SelfPaced
	- Self-Paced
	- Schedule allows for participation at a self-determined pace, though some specific dates and deadlines may be involved.
- schedule:OpenEntryExit
	- Open Entry/Exit
	- Schedule allows for the participant to enter, participate with, and complete the resource during any period of the resource's run time.
- schedule:OnDemand
	- On-Demand
	- Schedule allows the participant to choose when the resource begins.
- schedule:EventBased
	- Event Based
	- Schedule is determined or triggered by other events, such as completion of activities, completion of the resource, events external to the resource, or other events; refer to the resource's information for details.
- schedule:FullTime
	- Full-Time
	- Schedule is considered full-time.
- schedule:PartTime
	- Part-Time
	- Schedule is considered part-time.

It's intended to cover the generic descriptions of a course without getting too far into particular offerings of that course, but still solving the original use case that started this thread which was needing to identify things like "night" and "weekend" classes (which are still technically instance data, but it's hard to figure out exactly where to draw the line). It intentionally loosens the descriptions for "Monthly" and eliminates "Weekly" in favor of using a more broadly-defined "Weekdays" to allow for schedules like monday-wednesday-friday in addition to "all 5 weekdays". 

The idea is that a publisher of the data doesn't need to worry about looking up exactly what offerings for a given course exist for a given semester and determine whether or not the registry records (which are supposed to be abstract) need to be updated every semester. We can/should use some other means of capturing instance data for that, otherwise we're going to have the LearningOpportunityProfile problem all over again in terms of "it combines very different types of 'thing's".

**Comment by stuartasutton** [comment]
Somehow, I commented here and don't see my comment.  First, Phil's comment about "Nighttime" is valid for the US as well--it should be "Evening" to align with notions of daytime, evening, nighttime.  "Nighttime" shouldn't be included at all since I doubt that there are courses patterned to take place at midnight, learner time.

I think the days of the week should be included and declared as narrower concepts under "Weekdays" and "Weekends.

**Comment by jeannekitchens** [comment]
"Evenings rather that "Nightime" is appropriate.

**Comment by siuc-nate** [comment]
IWDS uses "Night" but I'm fine with "Evening" instead.

Re: listing the days of the week - I already gave my thoughts on this in earlier posts. I'm opposed to it for reasons described above.

**Comment by philbarker** [comment]
I think we have two separate dimensions in all the suggestions above

- frequency: one-off, yearly, monthly, (potentially weekly), full-time (which I take to mean more or less daily) 
- point of time: weekends, weekdays,  daytime, evening, self-paced

Having both aspects would let us distinguish between "every evening" and "once a week in the evening". As I said on the last call I don't think we can use one dimension as a proxy for something in the other, that is weekdays is not the same as weekly; daytime is not the same as daily; evenings is not the same as nightly (eveningly?).

In principle I've nothing against mixing the two in the same scheme with a single property, but obviously this falls down when there are different combinations offered.

It might be a step too close CourseInstance, but we could have them as spearate properties of a Schedule object, e.g.

{ "@type": "Course";
  "typicalSchedule": { 
      "frequency": "weekly";
      "approximateTime": "evening";
   }
}

Is that too close to CourseInstance @siuc-nate ?  Is it what's necessary to meet the use cases? I'm pretty sure it needs more discussion.

**Comment by stuartasutton** [comment]
I think your sense of dimensions is correct, Phil. I'd keep them in the same scheme using the skos:Collection with the SKOS capability of defining a collection with a a node label. I'm game to explore the a Schedule class.

**Comment by siuc-nate** [comment]
That probably treads too close to CourseInstance, especially for the use case here. I thought, in our discussion the other day, we decided to keep it high level. To me, that means the dividing line is where multiple selections could occur for different instances of the same Course, with some rule bending for very common/popular designations.  In other words, it's probably acceptable to indicate that a Course is offered in Daytime and Evenings on Weekdays, but to get any more specific than that is to get too far into what CourseInstance is for. Trying to represent a precise schedule is functionally the same thing, just without the other bells and whistles of CourseInstance.

Since scheduleType ("type" of schedule being what I would emphasize most, rather than it being an _actual_ schedule) would allow for multiple selections, that would look like:
```
{
	"@type": "ceterms:Course",
	"ceterms:scheduleType": [
		"schedule:Daytime",
		"schedule:Evening",
		"schedule:Weekday"
	]
}
```

**Comment by jeannekitchens** [comment]
I'd like to see the full proposal including those dimensions @philbarker.  Yes, sure...instance data could use that data but it is also generalizable enough and completely applicable.  All let's come up with the best approach for all of the terms and we will get feedback from the community.  This type of information is very common it is not just for instance data.

**Comment by philbarker** [comment]
What I could do is work up both options (single property, combined vocabulary and new object type, a couple of properties, separate concept schemes) and we can get input from a wider group of stakeholders. 

I think a single concept scheme makes sense with a single property, separate concept schemes if we have several properties.

@siuc-nate 
> Since scheduleType ("type" of schedule being what I would emphasize most, rather than it being an actual schedule)

I see you have Type in the property  name doing double duty there, it's a "type of schedule" and it's a CTDL convention for property referencing a concept scheme. I hope you pay it extra.

In your example, how do I know that 
```	
"ceterms:scheduleType": [
		"schedule:Daytime",
		"schedule:Evening",
		"schedule:Weekday"
]
```
means "during daytime hours, evening hours, and is on a weekly basis, Monday through Friday, consecutively or non-consecutively" not "there is a choice of daytime or evening on a choice of weekdays"(*)? I'm pretty sure that if we say one people will still use it for the other, if that's the information they expect to be able to publish.

We said keep it simple, but if it's too simple it will create more problems that it solves.

(* the more I look at this the more I realise that your sentence is ambiguous: sure it happens at those times, but is attendance at all required or are they alternatives?)

**Comment by siuc-nate** [comment]
>How do I know that ... means "during daytime hours, evening hours, and is on a weekly basis, Monday through Friday, consecutively or non-consecutively" not "there is a choice of daytime or evening on a choice of weekdays"(*)? 
>the more I look at this the more I realise that your sentence is ambiguous: sure it happens at those times, but is attendance at all required or are they alternatives?

The ambiguity is intentional, because to be any more specific is to delve into the realm of instance data. A Course may have two or three CourseInstances where one is during the Weekdays and one is during the Weekends (with one being Daytime and the other being Evening). Without CourseInstance, there would be no way to know which is which or what the possible combinations are.  That's a problem you'll have whether you have one property/vocabulary or two.  The only way to tie that together is with the Schedule object you mentioned earlier, but again, if you're going to create a Schedule object, why not go all the way and just create CourseInstance? 

Creating a Schedule object opens pandora's box: If you have specific schedules, then you'll need to tie those specific schedules to specific addresses. After all, it's not very helpful to say "One of this Course's schedules is a night/weekend class, and here are all of the places this Course is offered, but it's up to you to figure out which one(s) offer that night/weekend class". Additionally, those specific addresses may need to be tied to specific contact points. Rather than trying to bolt all of that onto an ever-expanding Schedule object, just create CourseInstance and be done with it.

However, since (as I understand it) we don't want that kind of instance data in the Registry, I don't think we should pursue that granularity of information.

The kicker is: Even if we did create CourseInstance, we would still be faced with the problem of describing the broad, generic, non-specific, non-instance **type** of schedule for that Course (ie an aggregation of the specific schedules of that Course's CourseInstances), so we would still be having this same discussion one way or another.

That is why I think we should, deliberately, use an ambiguous property/vocabulary for Course that allows for that kind of implicit aggregation of instance data into a broader and more generic summary of information that can be applied to the Course.  That way if we ever _do_ need to create CourseInstance, we can put all of the specific schedule/location/etc. stuff there.

**Comment by philbarker** [comment]
Sorry I had to leave the Nov 16 call rather promptly, but I think we agreed the following changes / additions to the proposal:
1.  Add `ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course, ceterms:AssessmentProfileceterms` to the domain of `ceterms:scheduleFrequencyType` and `ceterms:scheduleFrequencyType` so that in simple cases there is no need to use a `ceterms:ScheduledOffering` object.
2. Clarify that `ceterms:scheduleFrequencyType` relates to the "cadence" of the Learning Opp (etc), i.e. it is how often someone will have to turn up if they enrol.
3. Add a new term, something like `ceterms:offerFrequency` to cover how often Courses, Programs, Assessments, LearningOpportunities are offered, i.e. how long you might have to wait for the next chance to enrol.

@siuc-nate @jeannekitchens @stuartasutton Have I missed anything?

I think scheduleFrequencyType and offerFrequency can use the same concept scheme, but we should add one or new terms at the more frequent end to cover schedule frequencies that are more than weekly ("multiplePerWeek" and possibly "daily" would cover it, I don't think we want to be more precise than that.)

**Comment by philbarker** [comment]
Proposal for Dec 2021 TAG meeting:

Accepting we need location and delivery type in order to make sense of schedules, and that things like cost might vary depending on location/delivery type/ schedule; based on @siuc-nate's notes for #792: 

### Overview:
![Domai model additions](https://user-images.githubusercontent.com/658047/144616974-afe1ba76-fecd-48d5-98b4-18aa2bdf9048.png)

### New Class
> **URI:** ceterms:ScheduledOffering 
> **Label:** Scheduled Offering
> **Definition:** Offering of a Learning Opportunity or Assessment with a schedule associated with a specified location or modality.
> **Comment:** Provides data specific to a given scheduled offering; the Learning Opportunity (including Course and Learning Program) or Assessment being offered provides all data that is shared between different offerings.
> **Usage Note:** Rather than repeating data, only use this class if the data differs from the data provided by the resource for which this is an offer.

### New Properties

> **URI:** ceterms:hasOffering
> **Label:** Has Offering
> **Definition:** Indicates an offering and typical schedule.
> **Usage Note:** Only use this property when it is necessary and useful to provide data about specific offerings of a learning opportunity or assessment, such as particular combinations of schedule, location, and delivery.
> **Domain includes:** ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course, ceterms:AssessmentProfile
> **Range includes:** ceterms:ScheduledOffering

> **URI:** ceterms:scheduleFrequencyType
> **Label:** schedule frequency type
> **Definition:**  Type of frequency indicating the cadence at which events associated with a resource typically occur; select from an existing enumeration of such types. 
> **Comment:** This relates to the frequency of events associated with a resource once it is running
> **Usage Note:** For information relating to how often something starts, use ceterms:offerFrequencyType.
> **Domain includes:** ceterms:ScheduledOffering ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course, ceterms:AssessmentProfile
> **Range includes:** ceterms:CredentialAlignmentObject
> **Target concept scheme:** https://purl.org/ctdl/vocabs/ScheduleFrequency

> **URI:** ceterms:scheduleTimingType
> **Label:** schedule timing type.
> **Definition:** Type of time at which events typically occur; select from an existing enumeration of such types.
> **Domain includes:** ceterms:ScheduledOffering ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course, ceterms:AssessmentProfile
> **Range includes:** ceterms:CredentialAlignmentObject
> **Target concept scheme:** https://purl.org/ctdl/vocabs/ScheduleTiming


> **URI** ceterms:offerFrequencyType
> **Label:** offer frequency type.
> **Definition:** Type of frequency at which a resource is offered; select from an existing enumeration of such types.
> **Comment:** This relates to how often something starts. 
> **Usage Note:** For information relating to the frequency of events associated with a resource when it is running, use ceterms:scheduleFrequencyType.
> **Domain includes:** ceterms:ScheduledOffering ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course, ceterms:AssessmentProfile
> **Range includes:** ceterms:CredentialAlignmentObject
> **Target concept scheme:**  https://purl.org/ctdl/vocabs/ScheduleFrequency

### Modified Properties
**Add**
> **Subject:** ceterms:name
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:description
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:subjectWebpage
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:availableAt
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:offeredBy
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:deliveryType
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:deliveryTypeDescription
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:estimatedCost
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:commonCosts
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:estimatedDuration
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:aggregateData
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:availableOnlineAt
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

**Add**
> **Subject:** ceterms:availabilityListing
> **Predicate:**  schema:domainIncludes
> **Object:** ceterms:ScheduledOffering

### New Concept Scheme (Frequency)

> **URI:** ceterms:ScheduleFrequency
> **Title:** Schedule Frequency
> **Description:** Types for how often events occur.

### New Concepts (Frequency)

> **URI:** scheduleFrequency:SingleInstance 
> **Label:** Single Instance
> **Definition:** Schedule is a single instance of this event.
> **In Scheme:** ceterms:ScheduleFrequency

> **URI:** scheduleFrequency:Annually 
> **Label:** Annually
> **Definition:** Schedule is on an annual basis, typically occurring once per year.
> **In Scheme:** ceterms:ScheduleFrequency

> **URI:** scheduleFrequency:Monthly 
> **Label:** Monthly
> **Definition:** Schedule is on a monthly basis, typically occurring once per month.
> **In Scheme:** ceterms:ScheduleFrequency
 
> **URI:** scheduleFrequency:Weekly 
> **Label:** Weekly
> **Definition:** Schedule is on a weekly basis.
> **In Scheme:** ceterms:ScheduleFrequency

> **URI:** scheduleFrequency:MultiplePerWeek
> **Label:** Multiple Per Week
> **Definition:** Schedule is more frequent than a weekly basis.
> **In Scheme:** ceterms:ScheduleFrequency
 
> **URI:** scheduleFrequency:Irregular 
> **Label:** Irregular
> **Definition:** Schedule has no significant pattern.
> **In Scheme:** ceterms:ScheduleFrequency
 
> **URI:** scheduleFrequency:SelfPaced 
> **Label:** Self-Paced
> **Definition:** Schedule allows for participation at a self-determined pace, though some specific dates and deadlines may be involved.
> **In Scheme:** ceterms:ScheduleFrequency
 
> **URI:**  scheduleFrequency:OpenEntryExit 
> **Label:** Open Entry/Exit
> **Definition:** Schedule allows for the participant to enter, participate with, and complete the resource during any period of the resource's run time.
> **In Scheme:** ceterms:ScheduleFrequency
 
> **URI:** scheduleFrequency:OnDemand 
> **Label:** On-Demand
> **Definition:** Schedule allows the participant to choose when the resource begins.
> **In Scheme:** ceterms:ScheduleFrequency
 
> **URI:** scheduleFrequency:EventBased
> **Label:** Event Based
> **Definition:** Schedule is determined or triggered by other events, such as completion of activities, completion of the resource, events external to the resource, or other events; refer to the resource's information for details.
> **In Scheme:** ceterms:ScheduleFrequency

### New Concept Scheme (Timing)

> **URI:** ceterms:ScheduleTiming
> **Name:** Schedule Timing
> **Description:** Types for when in time events occur.

### New Concepts (Timing)

> **URI:** scheduleTiming:Daytime a skos:Concept
> **Label:** Daytime
> **Definition:** Schedule is typically during daytime hours.
> **In Scheme:** ceterms:ScheduleTiming
 
> **URI:** scheduleTiming:Evening  a skos:Concept
> **Label:** Evening
> **Definition:** Schedule is typically during evening hours.
> **In Scheme:** ceterms:ScheduleTiming
 
> **URI:** scheduleTiming:Weekdays a skos:Concept
> **Label:** Weekdays
> **Definition:** Schedule is Monday through Friday, consecutively or non-consecutively.
> **In Scheme:** ceterms:ScheduleTiming
 
> **URI:** scheduleTiming:Weekends a skos:Concept
> Label: Weekends
> Definition: Schedule is on a weekly basis, Saturday and/or Sunday.
> In Scheme: ceterms:ScheduleTiming

**Comment by philbarker** [comment]
I put the proposal above into a document in github, along with examples and links to diagrams, see [SchedulePatterns](https://github.com/CredentialEngine/Schema-Development/tree/master/SchedulePatterns) folder.

**Comment by philbarker** [comment]
As discussed in our March 1 call, I have updated the proposal to
add ScheduledOffering to the domain of ceterms:ctid e7f8dc821d017fe03163528fb5e832d80b26679c
add ScheduledOffering to the range of schema:about 8ce8fb41d75b196c3836cbce57ba6de1f19646be

@siuc-nate please confirm that I understood correctly what you suggested yesterday

**Comment by siuc-nate** [comment]
The changes for Scheduled Offering and related terms have been made in pending CTDL and noted in the history tracking (ditto for the change to schema:about within QData).

There are a lot of parts to this one so I would appreciate another set or two of eyes on it before I close the thread.
https://credreg.net/ctdl/terms?releaseid=pending
https://credreg.net/qdata/terms/about?releaseid=pending

**Comment by philbarker** [comment]
@siuc-nate good work, thanks, I see you fixed a couple of errors in the proposal (why aren't Concept Schemes in the /vocabs/ namespace URI scheme?)

Please check :
**Add**
> Subject: ceterms:deliveryType
> Predicate:  schema:domainIncludes
> Object: ceterms:ScheduledOffering

which I think you may have missed.

**Comment by siuc-nate** [comment]
Good catch, that one was in the history tracking but the change wasn't in the schema.  I have fixed it.

**Comment by philbarker** [comment]
## Registry Minimum Requirements
We need to set minimum requirements for ScheduledOffering in such a way that is doesn't get used when it is not necessary, i.e. it is only used if some aspect of the schedule, cost or other factor varies with location or modality. So:

**Optional on Assessment, Course, LearningOpportunityProfile, LearningProgram:**
ceterms:scheduleFrequencyType, ceterms:scheduleTimingType, ceterms:offerFrequencyType, ceterms:hasOffering

**Required for ScheduledOffering:**
- ceterms:ctid
- One of: ceterms:scheduleFrequencyType, ceterms:scheduleTimingType, ceterms:offerFrequencyType, ceterms:estimatedCost, ceterms:commonCosts, ceterms:estimatedDuration, ceterms:aggregateData
- One of: ceterms:deliveryType, ceterms:deliveryTypeDescription, ceterms:availableAt, ceterms:offeredBy

**Comment by siuc-nate** [comment]
I have updated the pending [policy](https://credreg.net/registry/policy#scheduledoffering) to reflect those requirement sets.

**Comment by jeannekitchens** [comment]
Included with March 29, 2023 CTDL release.  All new terms were released with as unstable.
