### ISSUE TITLE
Placement of the @context file in Competency Frameworks

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#783]
In the json-ld for competency frameworks output, the context file is not outside the graph statement but rather made local inside the CompetencyFramework description. 

```
{
    "@id": "https://credentialengineregistry.org/graph/ce-9704a892-c2cb-4395-bd7c-18a4d0d84ee9",
    "@graph": [
        {
            "@context": "https://credreg.net/ctdlasn/schema/context/json",
            "@id": "https://credentialengineregistry.org/resources/ce-9704a892-c2cb-4395-bd7c-18a4d0d84ee9",
            "@type": "ceasn:CompetencyFramework",
```

I need an explanation as to why it is not outside the graph and therefore global to it as found in the JSON-LD documentation.  I.e., as

```
{
    "@context": "https://credreg.net/ctdlasn/schema/context/json",    
    "@id": "https://credentialengineregistry.org/graph/ce-9704a892-c2cb-4395-bd7c-18a4d0d84ee9",
    "@graph": [
        {
            "@id": "https://credentialengineregistry.org/resources/ce-9704a892-c2cb-4395-bd7c-18a4d0d84ee9",
            "@type": "ceasn:CompetencyFramework",
```

**Comment by siuc-nate** [comment]
I'm not sure what you mean - it's working as it's supposed to:
![image](https://user-images.githubusercontent.com/21346519/128363693-2def5a09-a611-46df-98a8-c5433c0a5cb6.png)

Where are you seeing it with the context inside the framework node when loaded from the graph URI?

**Comment by stuartasutton** [comment]
I am looking at at the code through the lens of the Finder where the view of it has the context file inside the CompetencyFramework description and not outside the graph statement (1st code snippet above in my comment) which is a direct snippet from the viewer. It's correct in your code snippet, but not in the Finder.

**Comment by siuc-nate** [comment]
Oh, I see. That's a by-product of the way the framework detail page works and how it uses the description set functionality in the registry's APIs.  The graph record rendered there is composited from data that gets loaded through the description set API rather than being a raw copy pulled directly from the registry (in order to avoid fetching the same data twice, which would be particularly problematic for very large frameworks). I have fixed the compositing process to account for it. Good catch.

**Comment by stuartasutton** [comment]
Great. Closing
