### ISSUE TITLE
Modeling complex rules with Pathways

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#797]
When the Pathway's work was done, we defined a pathway (no pun intended) to expressing more complex rules for selecting pathway components from an array of candidates that go beyond the current "simple count rule". Since we were not prepared at that time to pursue how these more complex models should be modeled, the [ceterms:alternativeRuleSet](https://purl.org/ctdl/terms/alternativeRuleSet) property pointing to such rules was defined as "unstable".  We also made the decision that we'd define a [ceterms:requiredNumber](https://purl.org/ctdl/terms/requiredNumber) property on [ceterms:ComponentCondition](https://purl.org/ctdl/terms/ComponentCondition) to handle the widely used "simple count rule".  

The modeling of more complex rules is something we should approach cautiously and with input from additional **technical experts** beyond our core team which to me means a workgroup. I emphasize technical experts because the nature of the problem is clear; a solution that does not lead to a proliferation of properties is elusive. While I am sure we'll hear from some that the problem is too complex to solve in data, I do not think that is the case. There is no doubt that complexity presents thorny issues with regard to displays etc. and perhaps even search, but I do not think that we'll have a fully useful Pathway specification if it drops out the complexity of the original data.  

I did some initial thinking months ago about a suggestive  general approach illustrated in the following diagram.  The approach relies a bit on how the expression of complex rules are handled in the ODRL (Open Data Rights Language) specification. It's intended to be the beginning of a more structured work group conversation. *Until this happens, I think we need to place a moratorium on additional properties in the service of pathway rules.*

![Alternative Rule Sets](https://user-images.githubusercontent.com/2939046/141852317-c0f6f412-2cb5-430d-8b1d-e449568ab070.png)

Related to #796

**Comment by Lomilar** [comment]
This is heading down the direction in some sense of SCORM simple sequencing, where data structures are created instead of coding, math, or scripting languages.

It's possible (https://github.com/asvd/jailed) to run sandboxed code in a variety of environments, and I continue to prefer this to semantic math or logic operators structured in data.

To make a more measured argument:

Code is logic and math defined in serialized data where the format and schema are highly standardized and well understood, but unfortunately disjoint with data serialization formats and schemata. Reproducing such code in data for a purposeful standard is unnecessarily boutique. Conversion of abstract syntax trees (ASTs, the general form of coding language constructs) to and from data schema and languages would be an approach, but such conversions would be incredibly bloated in the data standard and create unwarranted confusion.

My expertise says: If you want logic represented in data, use serialized forms of that logic in common programming languages with a well defined software contract between the data structure and the encoded logic.

**Comment by siuc-nate** [comment]
If all we need to do is `(some left hand value) -[some math operator] -> (some right hand value)` then the proposed approach may be feasible (though I do not like the idea of adding a dozen math operator properties to CTDL that will almost never be used), but anything more than that and I agree with Fritz, you start getting into the territory of reinventing a programming language in RDF and I don't think we want to go down that road (at least not in CTDL, perhaps in its own namespace where the proliferation of properties wouldn't be an issue).

Instead, maybe (and I think this is what Fritz was getting at) something like a javascript string field with some means of indicating what to feed it and what to expect from it?  If the contract can be described in RDF without winding up with the same amount of complexity as the problem it's trying to avoid, then perhaps, but I'm not sure offhand how you'd do that.

**Comment by stuartasutton** [comment]
Fritz, [this](https://github.com/CredentialEngine/Schema-Development/issues/797#issuecomment-926718465) is exactly why I think we need a **workgroup** where we can discuss and vet approaches.  Just a quick (uninformed) observation: whatever the ultimate solution, a system wanting to express these more complex structures needs some system mechanism to instantiate a complex rule when it is handed one. This is true even with the "simple count rule".  It is possible in our data to express "Pick 2 out if the 5 candidates things"; but, some system consuming the data needs to operationalize the rule just as the Credential Finder pathways operationalize the "simple count rule".  Until convinced otherwise, I think there are two separate issues: (1) smart data that tells humans and systems what the rule being applied is, and (2) smart systems that operationalize the rules it is handed. 

This is likely a highly naive non-technical point of view.

We should probably stem a discussion off this issue since I think it will likely be extensive.

**Comment by stuartasutton** [comment]
Nate, my header labeling in the diagram is incorrect; these are not "properties" as the curly bracket points to "Concepts"; so they are concepts in concept schemes. At this very rough point, the only new properties are: 

>`logicalOperand` 
`leftOperand` 
`operator`
`rightOperand`

and tentatively...

> `candidateComponentRule`
`logicalConstraintRule`

AGAIN, LET'S PAUSE ANY FURTHER DISCUSSION.  
FOR ME, THE QUESTION HERE IS WHETHER WE SHOULD FORM A SELECT (PERHAPS INFORMAL) TECHNICAL GROUP TO WORK THROUGH A PROPOSAL.

**Comment by siuc-nate** [comment]
I appreciate the question you're focusing on, but I think answering that question does require some degree of discussion, at least enough to figure out whether or not there is a clear answer without need of such a group.

Am I understanding the intent correctly that this also needs to support things like nesting as well as logical ANDs and ORs? Trying to do that in structured data will get messy very quickly because of how such things are scoped.

**Comment by Lomilar** [comment]
Happy to work through a proposal. This problem isn't unique to pathways (computable rubrics, computable levels, informed data harvesting, etc) and we've taken some very uninformed swings at solving some problems in this space.

**Comment by stuartasutton** [comment]
Great, a formal Constraints Task Group has been formed. Fritz is correct that development should look at other analogous contexts where constraint solutions have been explored (e.g., [JsonLogic](https://jsonlogic.com/)).

**Comment by stuartasutton** [comment]
Ready to close. This issue is listed on the constraints github summary page: https://github.com/CredentialEngine/Schema-Development/tree/master/PathwaysConditionsAndConstraints
