### ISSUE TITLE
lifecycle of a competency

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#833]
Need publication status on Competency https://credreg.net/ctdlasn/terms#PublicationStatus

**Comment by stuartasutton** [comment]
@jeannekitchens, in the past, Competency Framework had a status that was applicable to the Competencies because the were part of the Framework. I think that is still a useful stance in framework-centric uses. In competency-centric uses, there is no reliable means to make the original inference; so, adding the status property to Competency makes sense; however, it would be useful to include a comment on ceasn:publicationStatusType like:

>With competencies that originate as part of a competency framework that includes an applicable publication status, it is not necessary to include that status on every competency in the framework.

**Comment by jeannekitchens** [comment]
@stuartasutton competency frameworks have a lifecycle but we know from NICE and OSN that collections of competencies have competencies that may be deprecated.  Agree with your comment above.

**Comment by philbarker** [comment]
I agree with Stuart

**Comment by jeannekitchens** [comment]
Let's move this forward please:
Need [publication status](https://credreg.net/ctdlasn/terms#PublicationStatus) added to Competency https://credreg.net/ctdlasn/terms#Competency
Add a comment to to [publication status](https://credreg.net/ctdlasn/terms#PublicationStatus): With competencies that originate as part of a competency framework that includes an applicable publication status, it is not necessary to include that status on every competency in the framework.

**Comment by stuartasutton** [comment]
I thought this was affirmatively resolved and that it was ready to go.

**Comment by siuc-nate** [comment]
This addition:
> **Subject:** ceasn:publicationStatusType
> **Predicate:** schema:domainIncludes
> **Object:** ceasn:Competency

Has been made in pending CTDL-ASN and noted in the history tracking.
