### ISSUE TITLE
Types of Certificates

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#836]
Certificates are commonly offered by postsecondary institutions that are intended for specializations at specific degree levels.  Indiana is running into issues with having to include a level with postsecondary certificates.  We have an audience level but we need to consider with our state partners adding postsecondary certificates such as:

- Graduate Certificate - Credential awarded at the graduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.

- Undergraduate Certificate - Credential awarded at the undergraduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.

  - Undergraduate  Lower Division Certificate - or maybe we need to look at lower and upper division rather than undergraduate because we wouldn't know if it's associate's level (i.e., lower division) or bachelor's level.   Credential awarded at the lower division undergraduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.
  - Comment (example)-  Intended for those in the first half of an undergraduate level program.
  
  - Undergraduate  Upper Division Certificate -   Credential awarded at the upper division undergraduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.

- Doctoral Certificate - Credential awarded at the doctoral degree level that designates requisite knowledge and skills of an occupation specialty,  profession, or academic program.

**Comment by siuc-nate** [comment]
All of these are covered by the use of audience level, it was explicitly created to enable this kind of detail, and mixing and matching.

**Comment by siuc-nate** [comment]
Additionally, creating very narrow sub-sub-subtypes of certificate defeats the purpose of using a schema in the first place: We already have terms for describing certificates with the above details, so creating more terms to say the things that can already be said will just lead (eventually) us back to square one wherein everyone is using their own words within their own silos and nobody is speaking a common language.

Using a common language requires some degree of translation. In this case, it is expanding information that they are packing into the name, out into the several properties that exist (and which others are using, and will be looking for) for conveying that information.

We would not want to apply this same logic to create dozens of other sub-sub-subclasses of certificate using data from other properties as well, e.g.
- ceterms:OnlineCertifiacte
- ceterms:OnlineUpperDivisionUndergraduateCertificate
- ceterms:GraduateTwoYearIndustryApprovedWeldingCertificate
- ceterms:InPersonOnlyLowerDivisionBachelorLevelVeteransFinancialAidCertificateOfCompletion
- ceterms:AssessmentBasedUndergraduateLevelNursingIndustryRecognizedFourYearDeprecatedBlendedDeliveryCertificate

And so on. Different data points belong in different properties for a very good reason. We have these properties already, and to lump them into more and more highly specialized sub-sub-subtypes will only hurt CTDL and its adoption.

**Comment by philbarker** [comment]
> Additionally, creating very narrow sub-sub-subtypes of certificate (or any other class) defeats the purpose of using a schema in the first place ...  creating more terms to say the things that can already be said will just lead us back (eventually) to square one wherein everyone is using their own words within their own silos and nobody is speaking a common language

Not true. The purpose of a schema (ontology, taxonomy) is to allow the creation of subtypes in such a way that connects the silos. This goes all the way back to "All Athenians are Greek; Socrates is an Athenian. Therefore Socrates is Greek". 

A classic example is Linnean taxonomies in biology. If I know the taxon trees Mammals > Primates > Homidae > Homo > _H. sapiens_ and Mammals > Primates > Homidae > Pan > _P. troglodytes_ then I can both find information for any Primate when that is what I want, and I can distinguish between Chimps and Humans should that ever be important.

**Comment by siuc-nate** [comment]
Branching/singular types work to an extent, but when you reach a level where there are a variety of options with varying combinations, it makes more sense to use other properties, as we are limited (by our systems) to just one type per object, but a variety of properties.  

In other words, a branching taxonomy makes sense for food > sandwich > burger because those are self contained enough to work as classes, but after that you should use other properties to indicate the presence or lack of cheese, lettuce, pickles, onions, etc., because so many different combinations are possible and it doesn't make sense to create a distinct class for every single possible combination.

**Comment by siuc-nate** [comment]
>This goes all the way back to "All Athenians are Greek; Socrates is an Athenian. Therefore Socrates is Greek".

You would not create a `Socrates` class; you would use the existing `Athenian` class and provide "Socrates" as the value of its `name` property. Otherwise you would need to create classes for every possible Athenian name.

>If I know the taxon trees Mammals > Primates > Hominidae > Homo > H. sapiens and Mammals > Primates > Hominidae > Pan > P. troglodytes then I can both find information for any Primate when that is what I want, and I can distinguish between Chimps and Humans should that ever be important.

That works fine as long as that's the only dimension you ever look at. But it would break down if you wanted to group primates together by which ones were tall, or smart, or old, or could dance, or live in the US, or were named "George", or countless other attributes. You wouldn't create more branches ala "Primates > GeorgeHomindae, Primates > TallHomindae, Primates > DancerHomindae" and so on.

If the only way we ever grouped credentials together was by level, then we could get away with the proposed changes. But we examine a wide variety of attributes of what makes up a credential.  Why should `audienceLevel` get mixed into the class name, but not `deliveryType`? Why not `estimatedCost` or `estimatedDuration` or `financialAssistance` or `accreditedBy` or whether or not an assessment is required? Why not mix any other properties into the class? What makes audience level so special? Furthermore, audience level applies to things other than certificates, so why wouldn't we then also create audience level variations of all of our other credential types, too?

What happens down the road when some other organization says "well, _our_ credentials are classified by their delivery types, and we'd really like to publish that, so you need to add `OnlineUndergraduateCertificate` and `InPersonUndergraduateCertificate` and `BlendedDeliveryUndergraduateCertificate` and `OnlineDoctoralCertificate` and `InPersonDoctoralCertificate` and `BlendedDeliveryDoctoralCertificate` and..."? What happens after that when some other organization groups their credentials by duration? And so on.

Additionally, even the proposed definitions point to the properties:
>Credential awarded at the graduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.

A "Credential that designates requisite knowledge and skills of an occupation, profession, or academic program." is a Certificate. A certificate with an `audienceLevelType` of `Graduate` would be exactly identical to a so-called "GraduateCertificate" as proposed, except that the `Certificate` and `audienceLeveLType` and `Graduate` terms already exist and are already in use.  It is completely redundant to create new classes like this. It will create confusion with regard to which terms should be used for publishing, which terms should be used for searching, it will create confusion in terms of "If I pick GraduateCertificate do I still need to indicate the audienceLevelType is Graduate?" and so on. It creates parallel languages for describing the same thing, which is exactly the opposite of what we are trying to accomplish.

**Comment by philbarker** [comment]
@siuc-nate you're missing the point with the Socrates example, maybe I should have explained more, but Athenian would be the more specific class (i.e. a Greek with citizenship of Athens). Socrates was an individual.

We could, in theory, have only one credential class and handle all differentiation by way of property values. That would be daft. Discussing daft examples and counter-examples isn't a good way to make progress, it just sets up a whole load of straw-men to be knocked down.

Something like "Undergraduate Certificate" is a sensible subclass of Certificate, more specific than a Certificate and not a Degree and represents a very common type of thing.  My only worry is that it highlights the difficulty in distinguishing Diplomas from Certificates in the current type list. In the  Heriot-Watt pathway example both [Certificate of Higher Education](https://en.wikipedia.org/wiki/Certificate_of_Higher_Education) (CertHE) and [Diploma of Higher Education](https://en.wikipedia.org/wiki/Diploma_of_Higher_Education) would be "Undergraduate Certificates".

**Comment by stuartasutton** [comment]
https://github.com/CredentialEngine/Schema-Development/issues/836#issuecomment-1189231921 +1

**Comment by siuc-nate** [comment]
>We could, in theory, have only one credential class and handle all differentiation by way of property values.

This is what I often wish we had done, as credential type would then be a concept scheme wherein multiple options could be selected to do a sort of soft-subclassing. In a lot of ways, this is (in effect) what we actually **do** do, often just for brevity, but also because all of the subclasses of credential are sufficiently similar as to be grouped this way.  For example, in our discussions, advertising, in our documentation, presentations, etc., we simply refer to "credentials".  In the finder, we have one "credential" search wherein credential type is just one of the filters like any other.  In practice, we _do_ just use a single Credential class and treat the types as a vocabulary.  This isn't reflected in the schema and having to bridge that gap every time I write a piece of code that has to tackle this is a never ending annoyance.

**Comment by philbarker** [comment]
Is that a serious suggestion? Assuming it is, I think that most online education providers aim for equivalence of outcome with in-person education providers, and so, while they wish to distinguish their courses as Online Courses, they do not wish to distinguish the credentials earned from those earned through other types of course.

**Comment by siuc-nate** [comment]
It was rhetorical. I could have also asked "Why not FourYearCertificate" or "FreeCertificate" or "AccreditedCertificate" or various other combinations of those (some of which may also involve audience level)

**Comment by philbarker** [comment]
> > We could, in theory, have only one credential class and handle all differentiation by way of property values.

> This is what I often wish we had done, as credential type would then be a concept scheme wherein multiple options could be selected to do a sort of soft-subclassing. 

I think the problem is that the role of classes in RDF and in OOP are entirely different. You can have your OO class of Credential and just treat the rdf:type as another attribute.

BTW, lots of concept schemes declare the concepts to be classes.

**Comment by siuc-nate** [comment]
Agreed, that has become painfully apparent over the last several years. But, all of our systems (and basically everyone else's) are OO whether we like it or not, so I have to make sure this schema will work within that context.

I suppose my main points are:
- You don't gain anything by creating multiple redundant ways to convey something that can already be clearly conveyed with existing terms
- If there are any gains, they are drastically outweighed by the problems created by doing so

**Comment by siuc-nate** [comment]
Per our 7-19-2022 meeting:
We will
- Do some modeling/examples to see how different approaches tackle this issue
- Look at use cases outside of Indiana, especially international ones, to identify approaches that work best
- Look at links to verifiable credentials and occupational credentials

**Comment by siuc-nate** [comment]
Using existing terms for the items from the original post:
```
{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:GraduateLevel"
    }
  ]
}

{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:UndergraduateLevel"
    }
  ]
}

{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:UndergraduateLevel"
    },
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:LowerDivisionLevel"
    }
  ]
}

{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:UndergraduateLevel"
    },
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:UpperDivisionLevel"
    }
  ]
}

{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:targetNode": "audLevel:DoctoralDegreeLevel"
    }
  ]
}
```

It would be good to collect additional examples as we discussed in our meeting, and ensure this approach will work for them as well. With the above examples, the venn diagram of "situations where you would use a Certificate with an audienceLevel" and "situations where you would use an AudienceLevelCertificate" is a circle.

**Comment by jeannekitchens** [comment]
Meeting with Ken and Jillian. Can check with institutions on 1a and 1b levels. 


**- Short-term** Undergraduate Certificate - Credential awarded at the undergraduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program. **Short-term, typically less than 1 year in duration.** **Equivalent to IPEDS Award Level 1a and 1b.**

  - Undergraduate  Lower Division Certificate - or maybe we need to look at lower and upper division rather than undergraduate because we wouldn't know if it's associate's level (i.e., lower division) or bachelor's level.   Credential awarded at the lower division undergraduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.  **Equivalent to IPEDS Award Level 1a and 1b.**
  - Comment (example)-  Intended for those in the first half of an undergraduate level program.
  
  - Undergraduate  Upper Division Certificate -   Credential awarded at the upper division undergraduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.  **Equivalent to IPEDS Award Level 1a and 1b.**

- Graduate Certificate - Credential awarded at the graduate degree level that designates requisite knowledge and skills of an occupation specialty, profession, or academic program.  **Equivalent to IPEDS Award Level 6.**

**Comment by siuc-nate** [comment]
We are failing to consider the problems this will create for downstream users/consumers of the data. Publishing issues only need to be solved once; search issues happen every single time a query is created. Therefore, we need to make sure that our partners are mapping to our schema, rather than creating a schema that will lead to confusion.

Under this proposal, all of these variations (and more) would be valid despite the redundancies:
```
Certificate A
@type: ceterms:Certificate
audienceLevel: UndergraduateLevel
estimatedDuration: <1 year
```
```
Certificate B
@type: ceterms:Certificate
audienceLevel: UndergraduateLevel, LowerDivisionLevel
```
```
Certificate C
@type: ceterms:Certificate
audienceLevel: UndergraduateLevel, UpperDivisionLevel
```
```
Certificate D
@type: ceterms:Certificate
audienceLevel: GraduateLevel
```
```
Certificate E
@type: ceterms:ShortTermUndergraduateCertificate
audienceLevel: UndergraduateLevel
estimatedDuration: <1 year
```
```
Certificate F
@type: ceterms:ShortTermUndergraduateCertificate
```
```
Certificate G
@type: ceterms:UndergraduateLowerDivisionCertificate
audienceLevel: UndergraduateLevel, LowerDivisionLevel
```
```
Certificate H
@type: ceterms:UndergraduateLowerDivisionCertificate
```
```
Certificate I
@type: ceterms:UndergraduateUpperDivisionCertificate
audienceLevel: UndergraduateLevel, UpperDivisionLevel
```
```
Certificate J
@type: ceterms:UndergraduateUpperDivisionCertificate
```
```
Certificate K
@type: ceterms:GraduateCertificate
```

Currently, if I want to find all of the certificates that would match all of the above, I just need to do a query like this:
```
{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": ["audLevel:UndergraduateLevel", "audLevel:LowerDivisionLevel", "audLevel:UpperDivisionLevel", "audLevel:GraduateLevel"]
}
```

With this change, I need to identify all of the types specifically (I can't use the subclass shortcut because that will include other kinds of certificates). I also have to account for some of those still being ceterms:Certificates. I also have to account for some of them having audience levels, and some of them not. All of that complicates my query:
```
{
  "search:termGroup": [
    {
      "@type": ["ceterms:Certificate", "ceterms:ShortTermUndergraduateCertificate", "ceterms:UndergraduateLowerDivisionCertificate", "ceterms:UndergraduateUpperDivisionCertificate", "ceterms:GraduateCertificate"],
      "ceterms:audienceLevel": ["audLevel:UndergraduateLevel", "audLevel:LowerDivisionLevel", "audLevel:UpperDivisionLevel", "audLevel:GraduateLevel"]
    },
    {
      "@type": ["ceterms:ShortTermUndergraduateCertificate", "ceterms:UndergraduateLowerDivisionCertificate", "ceterms:UndergraduateUpperDivisionCertificate", "ceterms:GraduateCertificate"]
    }
  ]
}
```

If I want to find the upper division certificates, currently I can just do this:
```
{
  "@type": "ceterms:Certificate",
  "ceterms:audienceLevel": ["audLevel:UpperDivisionLevel"]
}
```
But if I do that with the above changes, I will only find `Certificate C`, and miss all of the ceterms:UndergraduateUpperDivisionCertificates.

If I do:
```
{
  "@type": "ceterms:UndergraduateUpperDivisionCertificates",
  "ceterms:audienceLevel": ["audLevel:UpperDivisionLevel"]
}
```
I will likewise find `Certificate I` but miss all of the ceterms:Certificates at the upper division level (undergraduate or otherwise, like `Certificate C`), as well as any ceterms:UndergraduateUpperDivisionCertificates where the publisher forgot to tag them as being audLevel:UpperDivisionLevel (like `Certificate J`).

If I do:
```
{
  "@type": "ceterms:UndergraduateUpperDivisionCertificates"
}
```
I will find `Certificate` still miss all of the qualifying ceterms:Certificates (like `Certificate C`).

In order to catch everything, I need to not only know about all of these idiosyncrasies, I also need to complicate my query:
```
{
  "search:termGroup": [
    {
      "@type": ["ceterms:Certificate", "ceterms:UndergraduateUpperDivisionCertificate"],
      "ceterms:audienceLevel": ["audLevel:UpperDivisionLevel"]
    },
    {
      "@type": "ceterms:UndergraduateUpperDivisionCertificate"
    }
  ]
}
```

Basically:
1. This creates undue work and problems for downstream consumers, who have to know about all of the redundancies in the schema that have to be accounted for, as well as how to account for them
2. The above results in queries that are harder to write and debug, and less reliable because it's easier to miss things (ie false negatives)
3. Unless we require publishers to publish **all of the same data fields they would have to publish with the current schema anyway, completely negating any benefit to having hyper-specific subclasses**, downstream consumers will have an even harder time knowing if they've found all of the results they intended to find (imagine going to look for certificates and only finding a third of the ones that could have helped you because you simply didn't realize you had to look for the others too, or did so incorrectly)

There is **zero** benefit to adding these subclasses in terms of publisher workflow unless we are willing to _further_ sacrifice consumer workflow more than we already do. Adding redundancies in the data model for the sake of minor conveniences to publishers creates much bigger problems for consumers, who can more easily miss relevant data. No one's going to take us seriously if we keep allowing this kind of data model pollution.

What is the point of having the other properties and concepts if we're not going to use them for their intended purpose?

**Comment by jeannekitchens** [comment]
See GithHub Issue #914 that supercedes this issue.
