### ISSUE TITLE
Add availableFellowship property on CredentialOrganization and LearningProgram

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#858]
Add a ceterms:availableFellowship property to both ceterms:CredentialOrganization and ceterms:LearningProgram. 

>**URI:** ceterms:availableFellowship
**Label:** available fellowship
**Definition:** Short-term opportunity lasting from a few months to several years focussed on the professional development of the fellow that generally includes a living allowance or stipend under sponsorship of a specific organization seeking to expand leadership in a field.
**Domain:** ceterms:CredentialOrganization, ceterms:LearningProgram
**Range:** rdfs:Resource (discuss!)

See: http://www.collegescholarships.org/blog/2015/03/27/differences-between-scholarships-fellowships-grants-loans/

**Comment by siuc-nate** [comment]
For context, CTDL already has the following, which may help us figure out what to do here:

- [ceterms:LearningOpportunityProfile](https://credreg.net/ctdl/terms/LearningOpportunityProfile): 
  - Definition: "Entity describing an educational or training opportunity."
  - Comment: "Opportunities include formal and informal educational training programs and classes, apprenticeship or work experience programs, or other structured or unstructured experiences that serve as educational or training activities."
- [ceterms:ApprenticeshipCertificate](https://credreg.net/ctdl/terms/ApprenticeshipCertificate): 
  - Definition: "Credential earned through work-based learning and earn-and-learn models that meet standards and are applicable to industry trades and professions."
- [learnMethod:WorkBased](https://credreg.net/ctdl/vocabs/learnMethod/WorkBased): 
  - Definition: "Provides real-world work experiences that may be paid or unpaid and provided in group or individual formats normally outside the classroom."
  - Comment: "Applies to methods such as apprenticeships, internships, externships, work study, clinical rotations, residencies, practicums, field study, team projects, and cooperative education."

I would remove "short-term opportunity" since the range can be "from a few months to several years", the latter of which doesn't seem very short-term.  

Given all of that, I would capture a fellowship as follows:
- Use ceterms:LearningOpportunityProfile 
- with a ceterms:learningMethodType of learnMethod:WorkBased 
- with a ceterms:description and/or ceterms:learningMethodTypeDescription that details it as a fellowship and lays out the rest of the info as needed.  
- with a ceterms:hasOffering/ceterms:ScheduledOffering as needed to provide the offering info
- It can then be referenced from an organization or program via the usual ceterms:offers and ceterms:hasPart, respectively.  

If there is a need to call it out as a fellowship explicitly, then I would either:
- Create another Learning Method as a subclass of learnMethod:WorkBased that uses "Fellowship" in its label/definition (which would also tell someone who consumes the Learning Opportunity as a starting point that it is describing a fellowship, regardless of any connection to an organization or program), or
- Create the property proposed in the original post (though that does incur all of the usual caveats about making life harder for consumers/searchers of the data)

**Comment by siuc-nate** [comment]
I was leaning more into the definition and comment of WorkBased, which seems like it's broad enough to cover what you describe.  If a new Learning Method _shouldn't_ be a subclass of WorkBased, then so be it, but "being paid to do something for someone else" does seem like it falls into the broad category of "work" even if it is academic in nature.

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
