### ISSUE TITLE
Add learning method concept for apprenticeship and add registeredBy term

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#886]
Need to specify if an apprenticeship is registered with a govermental entity.  

E.g., Learning Program = Electrician Apprenticeship
Credential = Apprenticeship
Learning Method = Apprenticeship and Cohort Based
Registered Apprenticeship = True
The apprenticeship is registered with = name of governmental entity  or utilize a new "By" term.  E.g, ceterms:registeredBy - Agent that has registered the resource becuase it meets specific criteria. 

****Draft proposal:  
Add ceterms:registeredBy - Agent that has registered the resource becuase it meets specific criteria. 
Add learningmethod:apprenticeship - Formalized earn and learn program **** 

How it works example of a published apprenticeship program
Learning Program = Electrician Apprenticeship
Learn Method = Apprenticeship
RegisteredBy = URI or blank node.  Blank node example = name of organization, URL, organization description.

https://www.apprenticeship.gov/employers/registered-apprenticeship-program
“Registered Apprenticeships are industry-vetted and approved and validated by the U.S. Department of Labor or a State Apprenticeship Agency.”

URI: | https://purl.org/ctdl/vocabs/learnMethod/WorkBased
Shorthand URI: | learnMethod:WorkBased
Label: | en-US: Work Based
Definition: | en-US: Provides real-world work experiences that may be paid or unpaid and provided in group or individual formats normally outside the classroom.
Comment: | en-US: Applies to methods such as apprenticeships, internships, externships, work study, clinical rotations, residencies, practicums, field study, team projects, and cooperative education.

learnMethod:WorkBased URI: https://purl.org/ctdl/vocabs/learnMethod/WorkBased Shorthand URI: [learnMethod:WorkBased](https://credreg.net/ctdl/vocabs/learnMethod/WorkBased) Label: en-US: Work Based Definition: en-US: Provides real-world work experiences that may be paid or unpaid and provided in group or individual formats normally outside the classroom. Comment: en-US: Applies to methods such as apprenticeships, internships, externships, work study, clinical rotations, residencies, practicums, field study, team projects, and cooperative education.

**Comment by philbarker** [comment]
@siuc-nate are you wedded to the "real-world" characterizations? Just that as an academic I came across that in a pejorative sense very often from people who didn't think academia was "real world". Whatever you may think of that, lots of our constituency is in academia and we don't want to alienate them.    All work is work, so there is no need to qualify it in that way. Maybe if you do want to distinguish it from school-work it we could say "work with an employer" or similar.

While I appreciate the advantage of keeping to a consistent formula, Apprenticeship is more than work experience, I would characterize it as "work that is deliberately structured and supported so as to provide a progression of learning experiences"  

I don't have time to check it right now, but it would be looking at the [UNESCO TVETipedia Glossary](https://unevoc.unesco.org/home/TVETipedia+Glossary) for inspiration for defining these terms

**Comment by siuc-nate** [comment]
I borrowed those parts of the definitions from learnMethod:WorkBased, but I don't mind improving on them. I'm not sure where that phrasing originated, but Stuart did participate in crafting that definition, so hopefully it's not _too_ bothersome to our academically-minded friends.

Anyway, with all of those, I was trying to walk a line between being specific enough to distinguish one definition from another while not unintentionally excluding use cases we need these terms to cover. One thing @jeannekitchens had mentioned as the distinguishing factor between an apprenticeship and an internship is that with the former, you are effectively already hired for the job; not so much with the latter. I wanted to capture that without being too explicit about it.  Does that work internationally?

>Apprenticeship is more than work experience, I would characterize it as "work that is deliberately structured and supported so as to provide a progression of learning experiences"

In a loose sense, that is what I was driving at with "learning through ___" with each of those - keeping the focus/emphasis on these being learning methods.

**Comment by philbarker** [comment]
How about Apprenticeship: "Learning through work that is deliberately structured and supported so as to provide a progression of learning experiences."

Internships in the UK may be paid work and do count as employment. For me they're just a form of work experience, whereas an apprenticeship is a structured learning experience.

**Comment by siuc-nate** [comment]
I think we'll need to do a better job of distinguishing between apprenticeships and internships if we're going to break them into separate terms.  Jeanne's point was that apprenticeships are paid (since you are already hired) whereas internships may or may not be paid (and it's kind of ambiguous as to whether you are truly considered an employee, at least to me). 

It almost sounds like apprenticeships are a specific subset of internships? Admittedly I don't know enough about those kinds of details to speak with confidence, especially internationally.

**Comment by philbarker** [comment]
> I think we'll need to do a better job of distinguishing between apprenticeships and internships

Some things are widely understood but hard to define. I think that's true here. Anyone with an Apprenticeship / internship is likely to know which it is, and we can always have a usage note pointing out that WorkBased Learning  exists for cases that don't neatly fit into one or the other.

One key distinction that comes up in TVETipedia is that an [apprenticeship](https://unevoc.unesco.org/home/TVETipedia+Glossary/lang=en/show=term/term=Apprenticeship#start) leads to recognised qualifications;  whereas [internships](https://unevoc.unesco.org/home/TVETipedia+Glossary/lang=en/show=term/term=Internship#start) are shorter and do not aim to impart all the competences needed for a qualification.

(BTW **all the definitions of Apprenticeship collected by UNESCO in TVETipedia point to it being a type of program that includes classroom and work based learning rather than a learning method.**)

**Comment by siuc-nate** [comment]
We disaggregate notions in some places and leave them aggregated in others and I wish we were more consistent about that.  

If the only distinguishing factor between any program that includes classroom- and work-based learning and an apprenticeship is just "this one is called an apprenticeship and that one isn't", then I don't think we gain much by adding an apprenticeship subclass of program if that's what you're getting at (and I really don't want to have to factor in yet another flavor of Learning Opportunity Profile across all of our implementations).

It does give me an idea though:
>Some things are widely understood but hard to define.

We could lean into the idea of _identifying_ things rather than _defining_ them and create the Apprenticeship and Internship concepts which defer their definition to the publisher of the data, e.g.

learnMethod:Apprenticeship - Work-based learning that is considered an apprenticeship by the promulgating body
learnMethod:Internship - Work-based learning that is considered an internship by the promulgating body

It's kind of a cop-out and probably doesn't set the best precedent, but I worry that if we try to define those things, we will end up with publishers who don't quite see eye to eye with our definitions and then we'll end up with half a dozen subclasses of apprenticeship specific to each hair-splitting use case along the lines of our degree types.

Or, we could disaggregate the core ideas in play into concrete concepts:
- Paid work-based learning
- Unpaid work-based learning
- Employed work-based learning
- Non-employed work-based learning
- [Educationally] Structured work-based learning
- [Educationally] Unstructured work-based learning

Then publishers would pick the combination that correctly describes their data (whether they consider it an apprenticeship, internship, externship, whatevership becomes irrelevant and would likely be communicated via the program's name ala the subjects for the Degree subclasses), and consumers would have less guesswork to do (though it may raise some searchability concerns).  

The main thrust of the Pro Path use case is whether or not a program is registered, and we've figured that one out (hopefully), so needing to say "this is an apprenticeship" seems secondary to me (particularly if other non-apprenticeship things can be registered, too).

I don't think there is a good way for us to say "this is an apprenticeship" when "apprenticeship" can mean so many different things with no clear "right" definition for us to go with.

**Comment by stuartasutton** [comment]
This is a hard one since apprenticeships have a long history (at least in the US) as ladder work positions. For example I apprenticed as a retail grocery clerk--2,080 hours (equivalent to 1 year of full time employment) as an apprentice before advancing to journeyman clerk and a much nicer hourly wage. Many unionized jobs in the US have such a ladder structure that always begins as an apprentice and seldom entails a formal learning program; work is the program. But Phil has aptly identified the terms broader aspects. As a result, for me, duration and employer commitment are the most observable distinctions. Internships entail  short term commitments from an employer while apprenticeship entail an assumption of ongoing employment and ladder progression. Abraham Lincoln apprenticed for four years with a lawyer before earning journeyman status and the right to practice law unsupervised.

**Comment by mparsons-ce** [comment]
@jeannekitchens @siuc-nate @philbarker 
Chris from ProPath is now starting to work on updates for publishing related to registered apprenticeships. 

So we need to make a decision on:
- the learning method(s)
- confirm whether we are going to add RegisteredBy or RegisteredWith

**Comment by siuc-nate** [comment]
Per our 2023-9-12 meeting:
- We will use ceterms:registeredBy. People will read the definition to understand what it means (and that it does not mean "registered in the registry by ..."

**Comment by jeannekitchens** [comment]
Agent that has registerd the resource in a register because it has been vetted, approved and validated to meet specific criteria.

**Comment by siuc-nate** [comment]
I have added ceterms:registeredBy to pending CTDL. Since we still need to go over it with Phil, I have not yet put it in the history tracking (to save time making any further changes as needed).

For what it's worth, I think we have the definition pretty much figured out (though I would drop everything after "is registered" as it seems unnecessary), but I still think the property should be registeredWith instead of registeredBy, as that would better match the definition (and means we don't have a problem if we ever need to indicate who did the registering as opposed to who it's registered with).

**Comment by jeannekitchens** [comment]
The agent registers just as an agent approrves, recognizes etc..  It follows the pattern already establlished with the several "bys".  I'm fine with the definition.

**Comment by siuc-nate** [comment]
I would agree with you if the point we were trying to capture is "who submitted this resource to a list?", but we're trying to capture "whose list is this resource on?". It doesn't matter who submitted it, it matters whose list it is, because the maintainer of that list is the ultimate gatekeeper of what goes on it.

The fact that DOL happens to fill both roles in the Pro Path use case is causing the confusion here, I think. What if there were two different agents involved (one submitting things to the list and the other maintaining the list itself and deciding what gets accepted)?

My thinking, visualized (don't take any of this to imply proposals for new properties/classes/etc):
![image](https://github.com/CredentialEngine/Schema-Development/assets/21346519/f1439839-9ef1-4587-b8bf-d7bb591e7aeb)

Part 2:
![image](https://github.com/CredentialEngine/Schema-Development/assets/21346519/af9ac9f9-3e0a-487c-8de2-c9060abe7bae)

There are different verbs with different meanings:
```
(Course)-[registeredBy]->(Some Agent)
(Course)-[registeredWith]->(DOL)
```
And the inverses:
```
(Some Agent)-[registers]->(Course)
(DOL)-[registryIncludes]->(Course)
```

In a different context:
```
(Nurse ABC)-[registeredBy]->(Nurse ABC)
(Nurse ABC)-[registeredWith]->(State Licensing Board)

(Nurse ABC)-[registers]->(Nurse ABC)
(State Licensing Board)-[registryIncludes]->(Nurse ABC)
```
Which relationship is the one that actually matters in the end?

Maybe the problem is that we're actually using two different definitions of "registered"/"registers". I am using "registered/registers" to refer to the _submission_ of something to a registry, not the _accepting_ of that submission.

Maybe a slight change of verbs will clarify what I'm trying to say and the distinction I'm trying to make:
```
(Course)-[registrationSubmittedBy]->(Training Provider)
(Course)-[registrationAcceptedBy]->(Department of Labor)

(Training Provider)-[submitsForRegistration]->(Course)
(Department of Labor)-[acceptsRegistrationOf]->(Course)
```

**Comment by siuc-nate** [comment]
What about externships, residencies, etc.? If we ever need to make separate Concepts for those, we don't want to cover them with the above two terms now.

**Comment by jeannekitchens** [comment]
@philbarker good definitions. Just a couple of minor grammar changed are needed.

**Comment by philbarker** [comment]
Both Apprenticeship and Internship should reference [learnMethod:WorkBased](https://credreg.net/ctdl/vocabs/learnMethod/WorkBased) as a being skos:broader.

If externship and residency do deserve their own concepts we can (if necessary) indicate that they are skos:similar to these and use skos:scopeNote to explain when to use which. Externship in particular does not seem to be defined as being a completely separate concept (the name reflects this), and that is fine.

I made a couple of tweaks to the grammar by editing the post above, but let me know if I have missed anything.

**Comment by siuc-nate** [comment]
[These changes](https://github.com/CredentialEngine/Schema-Development/issues/886#issuecomment-1719631124) have been made in pending CTDL and noted in the history tracking.
