### ISSUE TITLE
Support Collections of Transfer Value Profiles

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#895]
1. Add [ceterms:TransferValueProfile](https://credreg.net/ctdl/terms/TransferValueProfile)to Range Includes for [ceterms:hasMember](https://credreg.net/ctdl/terms/hasMember)
2. Add [ceterms:TransferValueProfile](https://credreg.net/ctdl/terms/TransferValueProfile) to Domain Includes for [ceterms:isMemberOf](https://credreg.net/ctdl/terms/isMemberOf)

Supporting use cases where there needs to be groupings of transfer values that are out of scope for Transfer Value Intermediary.  There's several web pages on this site as examples https://partners.wgu.edu/general-transfer-guidelines.  Select any of the degrees to see the groups of possible course to course or credential (i.e., associates degree or bachelor's degree) to course potential transfers.

**Comment by philbarker** [comment]
@jeannekitchens   1 & 3 look like two ways of saying the same thing, am I missing something?

**Comment by jeannekitchens** [comment]
@philbarker that's what happens after spending too many hours staring at a screen;)  It is my mistake.

**Comment by philbarker** [comment]
I suppose it saves some effort somewhere to make a collection and point to it several times rather than point to all the members individually (so long as you do reference it more than once).

Is it too early to ask whether there is anything that should not be in a collection?

More importantly, we should be clear about what the semantics of pointing to a collection as the object of a statement. Do we mean one, some or all the things in a collection.

**Comment by philbarker** [comment]
I am very wary about the semantics of pointing to Collections.  The semantics of a property pointing to a collection are not the same as the property pointing to the members of the collection. For example

```
:phil :created :bookCollection

:bookCollection :hasMember :1984, :WiganPier, :AnimalFarm
```
Is very different from
```
:phil :created :1984, :WiganPier, :AnimalFarm
```
I created the collection, not create the books.

Creating collections so that they can be pointed to as a shortcut for pointing to all the members assumes the two have the same semantics.

**Comment by siuc-nate** [comment]
@philbarker A lot of where this issue came from was a meeting several days ago, I don't think you were part of it - but I think this particular usage is legitimate.  The objective was to enable a set of Transfer Value Profiles to be grouped together (not to be pointed at as a set, just to be together in a Collection).

To wit: We were looking at how to capture the data on this page:
https://partners.wgu.edu/general-transfer-guideline-bachelor-dynamic

And while there are still some issues around exactly what the nature of the individual Transfer Value Profiles (and their data) should be, I think we were pretty confident that the best way to host a list of them when needed is to put them in a Collection:
https://app.diagrams.net/#G1ak0XH3lm5z1vHILOqS5s5IhTP13LU2TC

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL and noted in the history tracking.

Feel free to reopen this issue if you have any additional thoughts @philbarker

**Comment by philbarker** [comment]
If the intent is just to say that there is a Collection of `TransferValueProfile`s  and it has these members, then that is fine.
