### ISSUE TITLE
New property: targetAction

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#920]
Major Use Case: As a QA Organization, I need to publish my QA Actions with a reference to ceterms:object.  I am not going to publish the (object) courses or learning programs on behalf of my customers.  I need my customers to publish their courses and learning programs and link those to the related QA action.  This enables more people and applications to find direct links between resources and related QA actions.

See Action data from Quality Matters in the sandbox. 

https://sandbox.credentialengine.org/finder/search?searchType=credentialingaction&filteritemtext=Quality%20Matters:%20Offers%2010%20Quality%20Assurance%20Action(s)&filterparameters={%22n%22:%22organizationroles%22,%22aid%22:3344,%22rid%22:[3,6,7]}

![image](https://github.com/CredentialEngine/Schema-Development/assets/20917206/028e4cac-878d-4d96-b09f-f647363fd698)

ceterms:objectOf
Definition: Action carried out upon this resource.
Domain: Credential, Learning Opportunity Profile, Learning Program, Course, Competency, Competency Framework, Assessment Profile, Credential Organization, QA Credential Organization, and Organization.
Inverse of ceterms:object.
Range: Action classes.

**Comment by siuc-nate** [comment]
Proposal:
**Create:**
**URI:** ceterms:targetAction
**Label:** Target Action
**Definition:** Action carried out upon this resource.
**Domain:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile (and subclasses), ceasn:Competency, ceasn:CompetencyFramework, ceterms:AssessmentProfile, ceterms:Organization (and subclasses)
**Range:** ceterms:CredentialingAction (and subclasses)

**Comment by siuc-nate** [comment]
Not to split hairs, but would a more proper URL/name for that definition be something closer to "Object Of Action" or maybe just "Object Of"?

Since the definition is not just a broad/generic "action related to this resource" style definition (which might be needed/useful later on) that we usually use with the "target" properties, I think having a more specific property name/label would make sense. That would also make it safe to declare the properties as being inverse of each other (I think we'd use [owl:inverseOf](https://www.w3.org/TR/owl-ref/#inverseOf-def) for that?)

I would propose:
**Create:**
> **URI:** ceterms:objectOf
> **Label:** Object Of
> **Definition:** Action carried out upon this resource.
> **Domain:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile (and subclasses), ceasn:Competency, ceasn:CompetencyFramework, ceterms:AssessmentProfile, ceterms:Organization (and subclasses)
> **Range:** ceterms:CredentialingAction (and subclasses)
> **Inverse Of:** ceterms:object

**Update:**
> **URI:** ceterms:object
> **Add owl:inverseOf** ceterms:objectOf

**Comment by philbarker** [comment]
I prefer Nate's [latest suggestion](https://github.com/CredentialEngine/Schema-Development/issues/920#issuecomment-1932486554). I would tend towards objectOfAction, because objects are all over the place in RDF / JSON-LD.

BTW: for the "broad generic action related to the resource" schema.org has https://schema.org/potentialAction "Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role." (if we ever need it)

**Comment by siuc-nate** [comment]
I updated the proposal to use "object of action".
@jeannekitchens @philbarker Are both of you on board with the proposal in my previous post?

**Comment by jeannekitchens** [comment]
@siuc-nate I'm good with this.

**Comment by philbarker** [comment]
@siuc-nate yep, looks good to me.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking
