### ISSUE TITLE
Correct Typo ceterms:targetLearningResource

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#926]
Correct the Definition: Learning object or resource that is used as part of an learning activity.

To: Learning object or resource that is used as part of a learning activity.

**Comment by siuc-nate** [comment]
We can collect all of the typos into a single github issue - no need to make a separate one for each.  Technically, typos don't really require a formal change anyway since they aren't intentional, so you can just send them to me when you find them and I can fix them.  The only time we might need an issue is if correcting a typo changes the meaning of the text (e.g. "do" instead of "don't")

**Comment by siuc-nate** [comment]
This has been fixed.
